### ISSUE TITLE
How does this library compare to react-lazy-load?

### ISSUE THREAD

**Issue by 0x80** [jasonslyvia/react-lazyload#100]
The `react-lazy-load` library seems to have been developed before this one, but has less activity in recent times. The API's are so similar that I find it a bit confusing.

What are the key differences that set these two apart?

**Comment by jasonslyvia** [comment]
This library was extracted and transplanted from a business project I developed in 2014, and honestly I didn't do much background investigation before I published react-lazyload to npm.

The key differences I'm aware now is probably react-lazy-load support horizontal mode and this project doesn't (currently).

**Comment by 0x80** [comment]
OK, thanks for clearing that up!
