### ISSUE TITLE
直接渲染懒加载生效 模拟请求获取数据 元素出现在视口内 图片不会加载

### ISSUE THREAD

**Issue by GlacierXX** [jasonslyvia/react-lazyload#102]
代码下图所示
![image](https://user-images.githubusercontent.com/7651252/26863182-8a581f5a-4b83-11e7-95d9-4b9bd0f9c277.png)
还有一个问题 如果height不设置 图片会全部被加载 如何优雅的去获取到图片的高度呢

**Comment by GlacierXX** [comment]
图片不加载的问题已经解决了 是因为CSS样式影响 关于在render前设置高度的问题 有没有什么好的方法

**Comment by jasonslyvia** [comment]
这个没有很好的方法，只能根据的自己的业务实际情况尽可能精确估算。
