### ISSUE TITLE
Npm install issue

### ISSUE THREAD

**Issue by andregoncalvesdev** [jasonslyvia/react-lazyload#103]
<img width="839" alt="screen shot 2017-06-13 at 19 02 43" src="https://user-images.githubusercontent.com/9271177/27097068-fce68110-506a-11e7-9294-6f19ad1931c8.png">

using node v7.10.0

**Comment by jasonslyvia** [comment]
hi, is this the output of just running `npm install react-lazyload`?

**Comment by andregoncalvesdev** [comment]
yes @jasonslyvia

**Comment by andregoncalvesdev** [comment]
I was using npm v5.0.1. Updated to 5.0.3 fixed for me.

Thanks.
