### ISSUE TITLE
Detection of scrollParent incorrect when overflow-x and overflow-y are set

### ISSUE THREAD

**Issue by davydog187** [jasonslyvia/react-lazyload#104]
Browser tested: Chrome 59

When making use of overflow scrolling, if the scroll parent is using `overflow-y: scroll` to set overflow scrolling, `react-lazyload` will incorrectly find the scroll parent when in `overflow={true}` mode. This is due to [this line](https://github.com/jasonslyvia/react-lazyload/blob/master/src/utils/scrollParent.js#L29), which is expecting `overflow`, `overflow-y` and `overflow-x` to all have values containing either `scroll` or `auto`. 

However, when `overflow-y` is set in chrome, the `getComputedStyle` value of `overflow` becomes `""` (empty string) as specified in the [CSS spec](https://drafts.csswg.org/cssom/#serializing-css-values).

The algorithm for detecting `scrollParent` needs to be re-evaluated to fix this bug. I was able to get around it by using `overflow: scroll` rather than `overflow-y: scroll`, but some others might not be so lucky.

Happy to put in a PR after some discussion.

**Comment by davydog187** [comment]
#98 Looks like its trying to fix a problem related to this, although it wants both `overflow-x` and `overflow-y` to be set, which i'm not sure is correct.

**Comment by jasonslyvia** [comment]
Can you test this PR against Firefox and let me know how it goes?

**Comment by davydog187** [comment]
@jasonslyvia what do you want to test?

**Comment by jasonslyvia** [comment]
If it works properly in Firefox

**Comment by jasonslyvia** [comment]
all overflow and scrollParent issue have been moved to #129 , let's discuss there
