### ISSUE TITLE
examples demo not working `Uncaught TypeError: Cannot call a class as a function` error

### ISSUE THREAD

**Issue by seoyoochan** [jasonslyvia/react-lazyload#11]
Most of your [demo examples](https://jasonslyvia.github.io/react-lazyload/examples/normal.html) not working due to the following errors.

```
Uncaught TypeError: Cannot call a class as a function
```

**[screenshot]**
![demo](http://i.imgur.com/Lj4p1C5.png)

**Comment by jasonslyvia** [comment]
Oops, huge mistake when switching branches, should be fixed now.

**Comment by seoyoochan** [comment]
@jasonslyvia thanks for your quick fix, but I found another problem.

[scroll_to.html](https://jasonslyvia.github.io/react-lazyload/examples/scroll_to.html) shows 1 to 8 pagination numbers, but the page only presents the LazyLoad only up to 6 components :open_mouth:

**Comment by jasonslyvia** [comment]
That is primarily due to a poorly designed demo, and it should work now (you have to scroll down to render the 7th and 8th element, then you can do quick jump using pagination above)

**Comment by seoyoochan** [comment]
@jasonslyvia yep. all of the demo works now! I appreciate that!
