### ISSUE TITLE
Callback for when component is loaded

### ISSUE THREAD

**Issue by oyeanuj** [jasonslyvia/react-lazyload#111]
Hi @jasonslyvia, wondering if there is any callback that is provided to know when the component is being loaded? This is super useful in advanced cases to do things when the component is loaded.

Thank you!

**Comment by jasonslyvia** [comment]
It is supported out of box, please refer to #65 for further information.

**Comment by oyeanuj** [comment]
Ah, missed this PR and didn't find it in the README. But thank you - this is what I was looking for!
