### ISSUE TITLE
Doesn't work when Parent container is display:none

### ISSUE THREAD

**Issue by lauterry** [jasonslyvia/react-lazyload#113]
Hi

I use Lazyload to lazy load youtube player to avoid loading youtube stuff (js, etc ...) on page load : 

```
<div>
<LazyLoad once offset={ 200 }>
	<iframe width="100%"
		height="100%"
		src={ youtubeUrl }
		frameBorder="0"
		allowFullScreen/>
</LazyLoad>;
</div>
```

It works perfectly !!!

However, if the parent tag have the css property ```display:none```, the youtube stuff (js. etc ..) is loaded on page load. I expect the youtube player to be load lazily.

```
<div style={ {display: "none"} }>
<LazyLoad once offset={ 200 }>
	<iframe width="100%"
		height="100%"
		src={ youtubeUrl }
		frameBorder="0"
		allowFullScreen/>
</LazyLoad>;
</div>
```

Best regards !

**Comment by jasonslyvia** [comment]
Good point, this feature needs careful parent (or event ancestor) element visibility change check, maybe it's better provided as an option.

**Comment by xuqingkuang** [comment]
@jasonslyvia How about check the one level parent only ?

**Comment by jonathantan** [comment]
@jasonslyvia Is it also the expected behaviour for lazy load to fail when "display: none" is set on the lazyload component itself? When I do that, the image downloads on page load.

**Comment by jasonslyvia** [comment]
It occurs to me that if you control your parent container's visibility dynamically, why don't you just render nothing instead of setting `display: none`, in which case LazyLoad will work just fine when it is rendered.

**Comment by jonathantan** [comment]
I'm currently using css to measure the screen size to decide whether to `display: none` on some images. I could use check the screen size on the react component but that requires a lot of extra work. I think it makes sense for lazyload to not load when an image has display set to none and that the fix could be an easy one line in index.js line 86 to check for node.offsetParent? https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent

**Comment by jonathantan** [comment]
I think commit 7abb292f520756ee612ce862f4babdcd9d15eb1d which checks for css visibility would fix the problem with display: none. Do you have plans to publish anytime soon?

**Comment by lidawang** [comment]
Oooh good catch, I didn't realize the package hasn't had a new release since that commit went in (I forgot to shepherd along a release). @jasonslyvia thoughts on supporting a new release before the React 16 support goes in?

**Comment by jasonslyvia** [comment]
@lidawang I think it's okay to release this before React 16 support, if there is any support that should be done, please help discuss in #125

**Comment by lidawang** [comment]
K, it's released! @lauterry @jonathantan Please upgrade to 2.2.8 to get the fix, lemme know if you have any issues!
