### ISSUE TITLE
Passing style props

### ISSUE THREAD

**Issue by Ehres** [jasonslyvia/react-lazyload#116]
Hello,

Is it possible to add passing style prop to children ? it would be useful for dynamic styles...

**Comment by jasonslyvia** [comment]
I guess just doing this will be fine

```javascript
<LazyLoad>
  <YourComponent style={yourStyle} />
</LazyLoad>
```

**Comment by Ehres** [comment]
My problem is if I would like map my children like this:
```
Children.map(children, (child, index) => (
  cloneElement(child, {
    style: {
      ...child.props.style,
      transitionDelay: `${index * (300 / children.length)}ms`
    }
  })
))
```

But now I think even in passing style it will not work...

**Comment by jasonslyvia** [comment]
Yeah, I fail to see how LazyLoad can do anything here.

**Comment by jasonslyvia** [comment]
closed for no further update
