### ISSUE TITLE
Breaks when testing using Jest

### ISSUE THREAD

**Issue by RamonGebben** [jasonslyvia/react-lazyload#119]
When I test a component that uses `LazyLoad` inside, my test fails at
`LazyLoad.componentDidMount (node_modules/react-lazyload/lib/index.js:276:7)`

I think the easiest solution would be to add a check to see if `findDOMNode` is available.
Any other suggestion on how to solve this?

**Comment by jasonslyvia** [comment]
This lib heavily depends on all kinds of DOM operations, I believe it's difficult (not impossible) to implement a mock-first test.
