### ISSUE TITLE
React 15 support ?

### ISSUE THREAD

**Issue by white87332** [jasonslyvia/react-lazyload#12]
Hi,
Any updates on this version?
Thanks

**Comment by jasonslyvia** [comment]
Currently it seems like just a update in package.json, I'll test it soon and publish a compatible version.

**Comment by jasonslyvia** [comment]
`1.6.2` is out, should be working. By the way I highly recommend you to try `2.0.0-beta.4`, which is also compatible with React 15.0.0 with more simpler API and better performance.
