### ISSUE TITLE
SSR - Unguarded references to window

### ISSUE THREAD

**Issue by andymueller85** [jasonslyvia/react-lazyload#121]
In preparation for converting my app to being server-side rendered I have added some unit tests that set global.window to undefined.  This caused errors coming from react-lazyload:

> TypeError: Cannot read property 'getComputedStyle' of undefined
      at exports.default (node_modules/react-lazyload/lib/utils/scrollParent.js:25:23)
      at checkVisible (node_modules/react-lazyload/lib/index.js:145:43)
      at LazyLoad.componentDidMount (node_modules/react-lazyload/lib/index.js:276:7)
      ...

This seems like it will cause issues when rendering on the server where window is unavailable

**Comment by jasonslyvia** [comment]
Which version are you using?

**Comment by andymueller85** [comment]
2.2.7

**Comment by jasonslyvia** [comment]
I'm sorry for such a late response, react-lazyload will only do DOM operation in `componentDidMount` which is not called in SSR situation, so you can safely use it for SSR.
