### ISSUE TITLE
Intersection Observer API

### ISSUE THREAD

**Issue by mrjackdavis** [jasonslyvia/react-lazyload#122]
Are there any intentions to implement this via the [intersection observer API](https://developers.google.com/web/updates/2016/04/intersectionobserver)?

Would be happy to contribute

**Comment by jasonslyvia** [comment]
Wow, I love this idea, how do you suggest we integrate this?

2017-09-18 10:07 GMT+08:00 Jack Davis <notifications@github.com>:

**Comment by mrjackdavis** [comment]
It'd be possible to use the `IntersectionObserver` API and [fallback on a polyfill](https://github.com/w3c/IntersectionObserver/tree/gh-pages/polyfill) or using the method you've got. It'd need a simple feature detect at the front. That was my plan before I found your package.

Thoughts?

**Comment by jasonslyvia** [comment]
I believe this API is a great replacement of [checkVisible](https://github.com/jasonslyvia/react-lazyload/blob/b06c646750d7822d89eeeb120ae2a94fbfcd727d/src/index.jsx#L114), the only concern is ployfill filesize.

**Comment by jasonslyvia** [comment]
let's discuss the posibility in #129
