### ISSUE TITLE
Doesn't work. componentDidMount of Widget component is called when LazyLoad component is mounted

### ISSUE THREAD

**Issue by wzup** [jasonslyvia/react-lazyload#123]
Here is a setup.

I have 20 items in state array. So 20 `<LazyLoad />` components are render initially. `UserItem` component is a Widget.

So UserItem's `componentDidMount` should be called ONLY when `<UserItem />` gets visible in a viewport, right? But the thing is that UserItem's `componentDidMount` is called right when `<LazyLoad/>` is rendered. So I get 20 server requests just immediately at once. No any lazy load. What's the secret?

```
<LazyLoad key={i} height={32} minHeight={32} once placeholder={<div className="loading"></div>}>
    <UserItem id={id} />
</LazyLoad>

UserItem.componentDidMount {
    // make server request here by props.id
}
```
Here is a screenshot. All requests are sent once at `12:47:49`. No any lazy load is observed. Although only 1/3 of the very first `UserItem` component was visible in a viewport.

![lazy load misbehavior - google chrome 2017-09-19 12 48 40](https://user-images.githubusercontent.com/3880497/30576253-44bb7fca-9d39-11e7-8933-1a8fe2bf4420.png)

**Comment by jasonslyvia** [comment]
It seems like your item's height is `32px`, then predictably your viewport must be larger than `32px * 20 = 640px`, which explains why all your 20 items are rendered at once.

In other case, if your items are contained in a overflow container, do add `overflow` props to `<LazyLoad>`.

**Comment by wzup** [comment]
Ok, I'll try to play with `height` option. 

Also, I've just examined [Widget](https://github.com/jasonslyvia/react-lazyload/blob/master/examples/components/Widget.js) component again and see that you use `componentWillReceiveProp` for a server request, not `componentDidMount` method. Why so? Is it crucial for the plugin to work correctly?

**Comment by jasonslyvia** [comment]
Because in this series of demo, there is an `id` passed from parent component, which if changed,  indicates new request is needed, and this `id` will change by clicking a global button.

You can safely send your request in componentDidMount if your request won't be affected by props change.

**Comment by wzup** [comment]
No, it doesn't work either.
A server request in `componentDidMount` is done for all at once. No lazy load.

**Comment by jasonslyvia** [comment]
Can you provide a reproducible demo so I can debug it?

**Comment by wzup** [comment]
`<LazyLoad>` component disappears when requests in `<Widget>`s are made and only `<Widget>` component stays after. In other similar plugin `<LazyLoad>` doesn't disappear, it wraps  `<Widget>` during all cycle and stays like that. And it works as expected - lazy load one by one when visible.

Should be like that all the way even when Widget;'s `componentDidMount` has been called:
```
<LazyLoad>
    <Widget />
</LazyLoad>
```

But it becomes like that. `<LazyLoad>` doesn't wrap `<Widget />` any longer. Is it correct behavior? Probably this may be a cause?
```
<Widget />
```

**Comment by jasonslyvia** [comment]
I'm confused without concrete code sample, but `LazyLoad` should not disappear in any means if you inspect your component tree using React Developer Tool for Chrome.

**Comment by jasonslyvia** [comment]
closed for no further update
