### ISSUE TITLE
Lazy load CSS background image?

### ISSUE THREAD

**Issue by chhuang** [jasonslyvia/react-lazyload#124]
Is it possible to lazy load the css background property?

**Comment by jasonslyvia** [comment]
I believe you can construct following component tree to achieve your goal:

```jsx
<LazyLoad>
  <Background>
    <YourComponent />
  </Background>
</LazyLoad>
```

in `Background` component, it can roughly be (pseudo code):

```jsx
function Background({ children }) {
  return (
    <div style={{ background: 'url(./kitty.png)' }}>
      {this.props.children}
    </div>
  );
}
```

**Comment by chhuang** [comment]
Got it! Basically it still lazy loading the HTML/component. That would do for now.

Thanks!

**Comment by Ajeetlakhani** [comment]
Is there any possibility for lazyload only the background image not whole component (textual content will be there only to lazyload bg image)?
