### ISSUE TITLE
placeholder as prop?

### ISSUE THREAD

**Issue by crossbreeze** [jasonslyvia/react-lazyload#13]
It would be nice to be abel to pass placeholder as prop to LazyLoad component so that instead of just showing blank spaces while scrolling down (default behavior), it could show custom component. (like loading message or progressing bar)

**Comment by jasonslyvia** [comment]
Currently you can style `.lazyload-placeholder` for some basic loading style, but yes a prop would be much more convenient.

**Comment by jasonslyvia** [comment]
released in `2.0.1`, here is a [demo](https://jasonslyvia.github.io/react-lazyload/examples/#/placeholder?_k=50vz9a)
