### ISSUE TITLE
SSR - Any way to render all while on server side and only lazy on client?

### ISSUE THREAD

**Issue by cainvommars** [jasonslyvia/react-lazyload#131]
I need the full page structure when doing server side rendering for seo and performance purposes. The moment the user starts navigating and stays in client land i'd like to lazy load some parts.

Any idea how to do that? Without returning complete different markup? Maybe a prop to disable the lazy functionality?

**Comment by jasonslyvia** [comment]
It's kind of duplicated with #109

**Comment by cainvommars** [comment]
@jasonslyvia You're right. It's a more general description of the same feature. Closing this ticket and will move the conversation over.
