### ISSUE TITLE
Issue on windows

### ISSUE THREAD

**Issue by mdfederici** [jasonslyvia/react-lazyload#133]
So I have an issue on windows where the lazy loaded component is clearly within the view screen but not loading. I am at 100% zoom if that makes a difference on windows in chrome 61. This is not an issue unless I'm on a small screen. I've been able to reliably reproduce it by having the chrome debugging tools open. Here is a screenshot for an example where my content is clearly on the screen but hasn't attempted to load.
![not loading even when on screen](https://user-images.githubusercontent.com/1938515/32278413-0caa71ca-beec-11e7-82a9-f4ec08d89e41.png)

And here is a screenshot for what happens when i scroll down just the tiniest bit (the content loads).

![a small scroll leads to loading](https://user-images.githubusercontent.com/1938515/32278421-1370e00c-beec-11e7-8fb1-94ca8ee01b78.png)

It seems as though the initial calculation of whether things are in view is incorrect in Chrome on Windows. FWIW, i do my development in chrome on a mac and cannot reproduce it there. My setup is as follows:

`<LazyLoad debounce={250} offset={400} placeholder={<div style={{height: '200px'}}><My Loading Componenet /></div>} >
        // my react component here
      </LazyLoad>`

What additional information can I provide to help this issue get diagnosed and/or fixed?

**Comment by mdfederici** [comment]
Leave it to rubber duck debugging... This isn't the bug i describe above. It's the fact that my loading height is much higher than the actual components end up being and so as they load, they bring additional components into view. Me deriving the height pre-load is fairly difficult as it could be a dynamic block of text as opposed to a fixed height object like an image. Is there a way for me to instruct lazy load to see if new components are in the viewport after other components have been loaded?

**Comment by jasonslyvia** [comment]
Maybe you need `forceCheck()` ? See the docs for more detail.

**Comment by mdfederici** [comment]
Sorry I should have been more clear. That seems like half of the puzzle but the other half is knowing when to call forceCheck. I'd want to call it after a component has loaded but i don't see any event being fired off or anything which i could hook into.

**Comment by jasonslyvia** [comment]
You can just do your 'after load' logic in your lazy loaded component's `componentDidMount` lifecycle method, as stated in the docs, this lib will render a placeholder instead of your actual component if it's not visible in viewport.

**Comment by mdfederici** [comment]
ok thanks
