### ISSUE TITLE
Issue with componentDidMount, refs, and LazyLoad?

### ISSUE THREAD

**Issue by randyridge** [jasonslyvia/react-lazyload#139]
I have a scenario where I have a parent component that lazy loads a child component and I need to get a ref from the child.  I expect the child to render and mount before the parent such that I can get the ref.

Without lazyload this works correctly (via some console logging):

1) parent render
2) child render
3) child mount
4) parent mount
5) img ref: Got ref!

When using LazyLoad:

1) parent render
4) parent mount
5) img ref: No ref!
2) child render
3) child mount

This caught me by surprise and so far I haven't found a workaround and it seemingly breaks getting refs for children that are lazyloaded...

I've attached a repro, you can comment/uncomment LazyLoad in Parent.js.

[repro.zip](https://github.com/jasonslyvia/react-lazyload/files/1494654/repro.zip)

**Comment by jasonslyvia** [comment]
I believe this is the expected behavior since, according to the documentation:

> You should aware that your component will only be mounted when it's visible in viewport, before that a placeholder will be rendered.

Btw, you should specify a number value for `height` props unless you clearly know what you're doing.
