### ISSUE TITLE
Support a onLoad callback function

### ISSUE THREAD

**Issue by lidawang** [jasonslyvia/react-lazyload#14]
It would be awesome if components that use `LazyLoad` can specify a callback that would be called when the component is in view for the first time (or just.... any time it comes into view, depending on if the `once` prop is used or not)

An example use case would be if a component needed to fetch some data once it comes into view.

**Comment by jasonslyvia** [comment]
You can safely fetch remote data in your component's `componentDidMount` lifecycle method, and `LazyLoad` will guarantee you that your actual component will only be mounted when it's visible in viewport.

**Comment by lidawang** [comment]
Oh! I didn't realize that, awesome. I'll modify our current use-case to do that then. Thank you!
