### ISSUE TITLE
对于`offset`值有点疑惑

### ISSUE THREAD

**Issue by lili21** [jasonslyvia/react-lazyload#144]
这个值是滚动条距离底部的值，还是组件顶部，距离可视区域的值？如果我想要让组件顶部距离可视区域x距离时就开始加载，应该怎么设置？

> Say if you want to preload a component even if it's 100px below the viewport (user have to scroll 100px more to see this component), you can set offset props to 100.

如果我没有理解错的话，这个是组件顶部距离可视区域的距离，但是实际上并没有这种效果，我的组件已经到可视区域了还没有开始加载。

**Comment by jasonslyvia** [comment]
麻烦提供一个可重现的 demo，否则不好调查具体出现什么问题。

**Comment by lili21** [comment]
[demo](https://codesandbox.io/s/40zoln4329)

比如这个。第二个图片一一开始就会加载，没有lazy的效果。需要设置height？

**Comment by jasonslyvia** [comment]
是的，需要设置 `height`，这是必选 props。

**Comment by lili21** [comment]
并不是必选吧？

那对于可适应的怎么处理呢？高度很多情况都不是固定的。

**Comment by jasonslyvia** [comment]
如果不固定，就设置一个平均值吧，你的 demo 设置 height 后是可以正确 lazyload 的。

2017-12-13 17:32 GMT+08:00 li.li <notifications@github.com>:

**Comment by smolak** [comment]
It would be great to know what this issue is actually about :)

**Comment by jasonslyvia** [comment]
yeah, English is always preferred when filing issues or discussing questions so we can cover more audience, and this issue is briefly about why you should always set `height` props to `LazyLoad` component.

feel free to open a new issue if you have further concerns :)
