### ISSUE TITLE
Does this works for a single but very long component ?

### ISSUE THREAD

**Issue by raghav-tayal299** [jasonslyvia/react-lazyload#153]
For example, If you have a long article with a lot of images in it. Does this lazyload the below-positioned images also?

**Comment by jasonslyvia** [comment]
I'm afraid you have to wrap each `<img>` into `<LazyLoad>` to lazy load them.

**Comment by raghav-tayal299** [comment]
Actually, my content comes as a single value from the database. So it won't be possible to wrap them separately. Maybe that can be an add-on for  'react-lazyload'.  Anyways thanks it's an awesome plugin. Solved a lot of my problems.

**Comment by jasonslyvia** [comment]
Maybe you can try some sort of technique that translate HTML to React Components and dynamically wraps `<LazyLoad>` around `<img>`.

**Comment by raghav-tayal299** [comment]
Thanks, I was also thinking of that.
