### ISSUE TITLE
Lazyload does not work when page is embedded as an iframe

### ISSUE THREAD

**Issue by steverob** [jasonslyvia/react-lazyload#164]
I have a page with a long list of components and I'm using your awesome library to lazily load those components as they come into view.

Recently I had to embed this page in other pages as an iframe with a fixed height on the iframe element.

In this setup, the components that are in the viewport when the page loads are the only components that are loaded EVER. As I scroll down inside the iframe, the other components never seem to be loading.

Is there an option or a workaround for this? Thanks!!

**Comment by eoinmurray** [comment]
This is also a problem for me
