### ISSUE TITLE
can we custom the container?

### ISSUE THREAD

**Issue by Pines-Cheng** [jasonslyvia/react-lazyload#168]
As the title said ,  the we use the `transform` Instead of `overflow:scroll` to make div scroll in the old project , and this too complex to refactor. 

therefore we try to find a way to pass a `id` or DOM node in to custom the scroll container ,Does this feature can be support?

**Comment by jasonslyvia** [comment]
Interesting point, I believe this is achievable by adding a props to define scroll implementation (eg. `normal` or `transform`) and do the checking respectively.

PRs are mostly welcomed!
