### ISSUE TITLE
Add class to placeholder container for overriding style

### ISSUE THREAD

**Issue by jrubins** [jasonslyvia/react-lazyload#17]
Currently if you provide a placeholder component, it is wrapped in a container DIV with `minHeight` set as an inline style:
```
render() {
    return this.visible ?
           this.props.children :
             this.props.placeholder ?
                <div style={{ minHeight: this.props.height }}>{this.props.placeholder}</div> :
                <div style={{ height: this.props.height }} className="lazyload-placeholder"></div>;
  }
```
This is problematic in my use case since I'm styling my placeholder to fit an aspect ratio, and the `minHeight` leaves some extra whitespace hanging around.

It seems like the styling of the container should either be removed and left to the consumer to implement or at least a class could be added to override any default styling.

If you agree with this and want me to do the PR, I can do that.

**Comment by jasonslyvia** [comment]
I get your point, but the problem of letting module consumer to add `height` or `minHeight` is unreliable, and if there isn't a `height` or `minHeight` set, LazyLoad would fail to calculate whether it's visible or not.

Guess we have to emphasize this in our docs, our do we have some enforcement checking to make sure `height` or `minHeight` exist?

**Comment by jrubins** [comment]
It seems like that would be something that could be emphasized in the docs - that the placeholder has to have some height in order for the visible calculations to work.

If you don't want to remove that inline styling, would you be up for adding a className to the placeholder _container_ to allow for (messy, but more targeted) overrides?

**Comment by jasonslyvia** [comment]
It seems reasonable, working on it.

**Comment by jasonslyvia** [comment]
fixed in 66d9e534517358c4e18503ecbdd441226364c255

 - [docs](https://github.com/jasonslyvia/react-lazyload#placeholder)
 - [test](https://github.com/jasonslyvia/react-lazyload/blob/d7e67f59905335a3c9338fbd4c652e9d55cfeaa3/test/specs/lazyload.spec.js#L120)

released 2.0.3

**Comment by SickSAMA** [comment]
Currently if I don't use a number height, there'll be a warning message. It's a bit annoying because I can use ```height={'100%'}``` or I can specify the height in css. In my view height should be optional

**Comment by jasonslyvia** [comment]
Yeah, I myself also hate warning, but for now I can't figure out a friendly and non-intrusive way to inform people using lazyload component without specifying `height` (I tried using `window.getComputedStyle` to find out if the `height` of the component being lazyloaded  exceeds a certain threshold, say `100px`, but that's inaccurate), and without a specified `height` lazyload might not work properly.

Thoughts?

**Comment by SickSAMA** [comment]
If no placeholder is provided, use thinks that lazyload will put a placeholder which has the same size as the real element. Then they just ignore the ```height``` option. In this case, the height usually will be 0. So warn the user if the height is not specified and 0. 

If a placeholder is provided, then the user should be responsible for his own element as it's not provided by lazyload. So no warning message is needed.

**Comment by jasonslyvia** [comment]
Cool, maybe I should reconsider the warning mechanism.
