### ISSUE TITLE
Should accept a custom container?

### ISSUE THREAD

**Issue by danieleleoni** [jasonslyvia/react-lazyload#173]
Hi guys,

we are trying to use LazyLoad inside a Markdown (react-markdown), and it works very good, but we get a warning because (for a moment, before image is rendered), we have a `<div>` under a `<p>`.

```
Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by LazyLoad)
```

This is an example we are working on
```
const renderLazyImage = props => (
  <LazyLoad height={200} offset={200} once>
    <img src={props.src} alt={props.alt} />
  </LazyLoad>
)

const Component = ({children}) => (
  <Markdown
    source={children}
    renderers={{
      image: renderLazyImage,
    }}
  />
)
```

It will be very useful for us to accept a different custom container, maybe a `p`?

This should be the point
https://github.com/jasonslyvia/react-lazyload/blob/master/src/index.jsx#L266

**Comment by danieleleoni** [comment]
For the moment I solved with a
`placeholder={<output style={{height: '200px'}}>&nbsp;</output>}`

Maybe it could help someone else

**Comment by jasonslyvia** [comment]
Yeah for your case I'd suggest using a custom `placeholder` and you did, so I think we're good here :)
