### ISSUE TITLE
Lazy load HTML content from dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by spondbob** [jasonslyvia/react-lazyload#178]
I tried to lazy load my component which basically loading HTML string into a div with
```
<div dangerouslySetInnerHTML={{__html: "<div><img /><img /><img /></div"}} />
```
But it did not seem lazy loading the images. Is this behaviour expected when images are loaded through `dangerouslySetInnerHTML`? How can I achieve this?

**Comment by jasonslyvia** [comment]
I believe there is no way to lazy load content of `dangerouslySetInnerHTML` since they're not React Component, if you can turn your html into some structured json or something maybe you can do:

```jsx
{json.map(line => {
  if (isImage(line)) {
    return <LazyLoad><img src={line} /></LazyLoad>;
  }

  return <div>{line}</div>;
})}
```
