### ISSUE TITLE
Will support effect fadeIn？

### ISSUE THREAD

**Issue by ibufu** [jasonslyvia/react-lazyload#18]
just like http://www.jq22.com/yanshi390

**Comment by jasonslyvia** [comment]
It's up to you to do any effect when component is loaded, but I think adding a demo won't hurt.

**Comment by jasonslyvia** [comment]
Checkout this [demo](https://jasonslyvia.github.io/react-lazyload/examples/#/fadein).

**Comment by ibufu** [comment]
I have seen that demo. But I'd like to use this style:
```javascript 
<Lazyload throttle={200} height={300} efftect={'fadeIn'}>
     <img />
</Lazyload>

**Comment by jasonslyvia** [comment]
Yeah, I don't really think react-lazyload would take this responsibility.

**Comment by jasonslyvia** [comment]
I'm gonna leave this issue open and see what anyone else thought.

**Comment by jasonslyvia** [comment]
Since no one expresses the same intention, I'm closing this for now.
