### ISSUE TITLE
Update decorator property in runtime

### ISSUE THREAD

**Issue by murilo-campaner** [jasonslyvia/react-lazyload#180]
Its possible to update an decorator property in runtime?

My problem is the following, I have a component that uses the LazyLoad decorator like this:

`@lazyload({
    once: true,
    offset: 200,
    overflow: false
})`

But, I need update the property overflow in runtime of my component, because I receive that value as prop from parent component.

How I can do this? Can anyone help me with a solution or a workaround?

**Comment by jasonslyvia** [comment]
based on your situation, maybe you should just use the `LazyLoad` component

**Comment by murilo-campaner** [comment]
Yes, I created a HOC to do this... Thank you
