### ISSUE TITLE
Stopped working when navigate

### ISSUE THREAD

**Issue by murilo-campaner** [jasonslyvia/react-lazyload#181]
Hello,

I'm with the following problem...

The LazyLoad component is working well in same page, but when I click in a button and navigate to another screen and then I click on navigate back to previous screen, it doesn't reload my lazyloaded components.

I already tried to use forceCheck on componentDidMount of my container.

![ezgif-4-2a33cc01ea](https://user-images.githubusercontent.com/22455216/40705484-65268d32-63c1-11e8-91ab-8685a15971e4.gif)

Anyone can help-me? Thank you

**Comment by jasonslyvia** [comment]
is there any console error?

**Comment by murilo-campaner** [comment]
That was a problem with height property.... I don't know why... But when I removed this property it worked fine...
