### ISSUE TITLE
Support an `onLoad` prop

### ISSUE THREAD

**Issue by garrettmaring** [jasonslyvia/react-lazyload#185]
It'd be nice to be able to provide an `onLoad` function as a property which would be invoked with the component that is loading.

**Comment by gdenisov** [comment]
@garrettmaring I was looking for the same functionality, but after thinking about it for a little bit I think onLoad should be provided by the child component anyway as LazyLoad component itself nothing about what would be loaded and how.

**Comment by jasonslyvia** [comment]
@gdenisov is right, LazyLoad will guarantee you that your component only will mount when visibility condition is met, so you can safely do what you want in your component's `componentDidMount` lifecycle method.
