### ISSUE TITLE
Ready to maintain

### ISSUE THREAD

**Issue by ameerthehacker** [jasonslyvia/react-lazyload#194]
Hey @jasonslyvia i'm interested in supporting and maintaining this project.

**Comment by jasonslyvia** [comment]
really appreciate your support, thanks! an invitation for collaborator has been sent, please checkout GitHub notifications.

**Comment by ameerthehacker** [comment]
Thanks @jasonslyvia i have accepted

**Comment by jasonslyvia** [comment]
feel free to let me know when you need to publish a new package to npm :)
