### ISSUE TITLE
An error is reported if the child node is not a dom object

### ISSUE THREAD

**Issue by cnyballk** [jasonslyvia/react-lazyload#197]
An error is reported if the child node is not a dom object
For example：
```jsx
<LazyLoad>I'm a text</LazyLoad>
```
This is because subsequent operations assume that the child node is a dom object,

```js 
if(!node){
 // omit
} 
```
just determine (!node) is not enough

**Comment by ameerthehacker** [comment]
Thanks @cnyballk I too tried the same and faced the same issue and your fix was perfect Thanks!
