### ISSUE TITLE
Sometimes all images get loaded at once

### ISSUE THREAD

**Issue by bramvdpluijm** [jasonslyvia/react-lazyload#198]
I have a very simple page setup. It's a container with images underneath each other. Sometimes all images get loaded at once. I don't know why this happens. All my <LazyLoad /> elements have heights set.

**Comment by ameerthehacker** [comment]
hey @bramvdplujim can you please share your issue using jsfiddle

**Comment by jwilson64** [comment]
I can get it to hit here and it also renders kind of funny:
https://codesandbox.io/s/jzjzzr594y
