### ISSUE TITLE
Items loaded is reload when scroll

### ISSUE THREAD

**Issue by thanhphuongphan** [jasonslyvia/react-lazyload#203]
I have use child component nested in react lazyload and its in the loop. At parent every scroll below, I will call fetch data at child component. Currently, the first loading and show data that right, but when I do scoll below, reload items above and the items at viewport. I have attach image and code. Can you help me resolve problem, please? Thank so much.

![first](https://user-images.githubusercontent.com/38026546/46851222-fc2ec900-ce20-11e8-89f7-1cdd2f96089a.png)
![second](https://user-images.githubusercontent.com/38026546/46851220-fb963280-ce20-11e8-9b09-3f1798516ab4.png)

Code:
https://jsfiddle.net/phuongpt0301/n5u2wwjg/211750/

**Comment by RezaGhx** [comment]
@thanhphuongphan If you found the solution, please share it. otherwise, please check the new issue I've submitted.
