### ISSUE TITLE
How can I use react-lazyload with react-flip-move

### ISSUE THREAD

**Issue by mmarkelov** [jasonslyvia/react-lazyload#216]
Can I do force update when component is in focus?
I tried to use **react-lazyload** with **react-flip-move**, but I got some problems:
![problems](https://media.giphy.com/media/5bgGGlGiblOPFb7H14/giphy.gif)
Also you can check it on codesandbox:
[![Edit lw2rpl81z](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lw2rpl81z)
Thanks!

**Comment by mmarkelov** [comment]
@jasonslyvia that's work for me. Thanks!

**Comment by shunmian** [comment]
Hi, @mmarkelov , I'm trying to use `react-flip-move` with `react-lazyload` but the animation doesn't work. Do you mind check the above code sandbox since it return 404.
