### ISSUE TITLE
parent shouldn't be document?

### ISSUE THREAD

**Issue by VinSpee** [jasonslyvia/react-lazyload#22]
Hi!

I'm currently rendering my react app to a node that isn't the root - it's about 1/3 of the way down the page. It looks like it's grabbing the first div inside body and adding `data-lazyload-listened="1"` to it, not the react root, causing everything to load after the first render, even if it isn't in the viewport.

Am I doing anything wrong?

**Comment by jasonslyvia** [comment]
Can you share some snippets?

**Comment by jasonslyvia** [comment]
Feel free to provide further information and I will reopen this issue.
