### ISSUE TITLE
Add a forceCheck() function to fix update bug

### ISSUE THREAD

**Issue by SickSAMA** [jasonslyvia/react-lazyload#26]
Thank you for this library, nice work. I'm using it in my project. Currently it only listens to `scroll` and `resize` event for update. However, sometimes not only these two events trigger position change.

Imaging a react component renders a grid system which half of grid items are below the viewport. After the component re-renders, if only 1 item is remaining and it was below the viewport before, it is not re-rendered and it's lazyload `checkVisible` won't get called even thought is above the fold now.

One solution can be adding a forceCheck function to to check all invisible lazyload components in the parent component's `componentDidUpdate`.

**Comment by jasonslyvia** [comment]
How about exporting `checkVisible()` function and you can call it anytime your layout might change?

```javascript
import LazyLoad, { checkVisible } from 'react-lazyload';
```

**Comment by SickSAMA** [comment]
Yes, that's exactly what I want.

**Comment by jasonslyvia** [comment]
It seems achievable, do you might sending a PR?

**Comment by SickSAMA** [comment]
Maybe wrap the `checkVisible()` to check all components in `listeners`?

**Comment by jasonslyvia** [comment]
Yes, that's necessary, how about exporting a new method called `forceCheck` and it will check all components in `listeners`.

**Comment by jasonslyvia** [comment]
Basically that's just what you suggested 😂

**Comment by SickSAMA** [comment]
Shall I send a PR?

**Comment by jasonslyvia** [comment]
Sure, please.

**Comment by jasonslyvia** [comment]
released as `2.1.2`, thanks for your endeavour.
