### ISSUE TITLE
Not working (probably my mistake, though)

### ISSUE THREAD

**Issue by reintroducing** [jasonslyvia/react-lazyload#28]
Hello,
I'm trying to use this component inside of a custom Image component. It's quite simple, a stateless functional component. It looks as follows:

```
import React, {PropTypes} from 'react';
import classNames from 'classnames';
import LazyLoad from 'react-lazyload';

const Image = ({alt, className, lazyLoad, ...imgAttributes}) => {
    const classes = classNames(
        'Image',
        className
    );
    const img = <img alt={alt} className={classes} {...imgAttributes} />;

    if (lazyLoad) {
        return (
            <LazyLoad throttle={200} height={300}>
                {img}
            </LazyLoad>
        );
    } else {
        return img;
    }
};

Image.propTypes = {
    className: PropTypes.string,
    /** Descriptive information about what is in the image. Do not use the words image, photo, or picture. */
    alt: PropTypes.string,
    lazyLoad: PropTypes.bool
};

Image.defaultProps = {
    className: '',
    alt: null,
    lazyLoad: false
};

export default Image;
```

I then call it like this:
```
<Image src="http://placehold.it/550x400" alt="Just a temporary placeholder" lazyLoad />
```

I don't see the placeholder div and my image automatically gets rendered into the DOM without me scrolling to it (it's pretty far down).  Even if I replace all of the logic for testing lazyLoad and displaying the correct thing, or remove it completely and just show the LazyLoad wrapped around an image, I still see the image rendered into the DOM automatically in the elements panel.

Is there anything I'm doing wrong here?

**Comment by jasonslyvia** [comment]
Try add appropriate style (eg. `height`) for elements above your `Image` component, or when lazyload calculating whether your components are visible or not, it will get lost.

**Comment by reintroducing** [comment]
That does not seem to have worked.  I even tried adding the same height to the LazyLoad component but still nothing: https://www.dropbox.com/s/ho180st3qn3scwx/Screenshot%202016-06-05%2008.10.20.png?dl=0

**Comment by jasonslyvia** [comment]
Let's say your App renders a layout like this:

![image](https://cloud.githubusercontent.com/assets/1336484/15809772/98de4d40-2bc9-11e6-814b-ed1dc6530920.png)

Have you set appropriate `height` for Component A, B, C, D, E?

**Comment by reintroducing** [comment]
No, and I really shouldn't have to, should I? I don't think a user should have to be setting the heights of every single component on the page to make sure that this particular component using LazyLoad works properly. It should be smart enough to calculate its position in the viewport without knowing anything about any other components.  Am I missing something here?

I went ahead and switched over to react-lazy-load and it's working as expected but I'd still love to help you troubleshoot this so that we can get this resolved if you're up for it.

**Comment by jasonslyvia** [comment]
Hmm, maybe I should rephrase. 

You don't have to explicitly set `height` for those components above, but you should make sure when initial rendering is done, `<Image />` is literally not visible in viewport.

Because in some cases involves with async data and re-render, the initial render will render nothing or a `<div>` with `height` much less than it's populated with data. At that moment, LazyLoad will do some calculation and determine your image should be visible.

If you can kindly provide a testing repo, or at least related dependency versions, I will dig into this issue.

BTW, I'm sorry for bringing you inconvenience :(

**Comment by reintroducing** [comment]
It's not an inconvenience at all, don't worry about it.  :)

I can assure you the component is not within view.  What I'm currently working on is preparation for a brand new project and I'm building out the UI kit. In other words, a bunch of components that are going to be used throughout the project as part of the UI.  I've just got one page with all these components and the Image component is one of the last on the page.  There is literally like 6000px of scrollable area before Image is ever in the viewport.

I'll try my best to set up a reproduction of the issue but I can't promise when that will happen.  This is a freelance project on top of my day job so time is sparse at the moment.

**Comment by jasonslyvia** [comment]
Oh wait, can you check if you're scrolling the `document.body` or a container `<div>` ?

**Comment by reintroducing** [comment]
I'm just scrolling the body using a native browser scroll bar, just lots of content on a page being scrolled normally.

**Comment by jasonslyvia** [comment]
Alright then...

**Comment by jasonslyvia** [comment]
closing for no further updates
