### ISSUE TITLE
Filter list does not trigger checkVisible

### ISSUE THREAD

**Issue by vinceprofeta** [jasonslyvia/react-lazyload#29]
I have a list component where I load in lazyload and I have a filter bar that filters the location. If a location result is not in the current scrolled view the checkVisible method does not get called resulting in the component no getting loaded in. 

triggering a scroll event programmatically on the overflow element did not seem to work.

I added a custom event and triggered that when searching, this worked as a quick hack.

Any ideas for being able to pass in a custom event or being able to trigger an event programmatically (maybe just on the window) to trigger checkVisible

**Comment by jasonslyvia** [comment]
You can manually call `checkVisible` like this:

```javascript
import { forceCheck } from 'react-lazyload';

obj.on('filter', forceCheck);
```

**Comment by jasonslyvia** [comment]
Closing for no further update.
