### ISSUE TITLE
Wrong scrollParent

### ISSUE THREAD

**Issue by fatlinesofcode** [jasonslyvia/react-lazyload#30]
The scrollParent method isn't always reliable for finding the correct scrollable Parent element. It will return a false positive is another parent other the scrollable one has an 'overflow' style. Ideally you should be able explicitly specify the parent element you want to use. Something like this:

```
<LazyLoad overflow={true}  scrollParent=".scroll-div" >
```

within the scrollParent function you could simply return

```
return document.querySelector(props.scrollParent);
```

**Comment by cnolimit** [comment]
was this implemented? i wanted a way to define the parent element so i could then set my offset from there.

**Comment by jasonslyvia** [comment]
there's a pending pr, but got no update since then.

2016-08-17 21:26 GMT+08:00 Phillip Boateng <notifications@github.com>:

**Comment by stahlmanDesign** [comment]
adding overflow={true} solved the problem for me

**Comment by jasonslyvia** [comment]
closing for no further information provided
