### ISSUE TITLE
lazyload is not working when integrating with some third-party UI frameworks(css).

### ISSUE THREAD

**Issue by sdmgeek** [jasonslyvia/react-lazyload#32]
Thanks for creating such a great lazyload component for react!
Recently, I tried using this package for the effect of lazyload.
After added this component to a page, I found there's nothing happened.
Then I cloned the provided examples and ran it on my localhost, it just worked.
So I rebuilt my page again step by step using the example as a base, it still worked so great.
Finally, I added a thirty-party css to the page and lazyload broke.

I just add a link tag to page
\<link rel="stylesheet" href="http://grommet.io/assets/latest/css/grommet.min.css">

Could you help debugging which part of the css breaks the lazyload component?
It's a pity that the nice-looking UI framework can't work with lazyload component.
I think perhaps that people will find some other UI frameworks that have the same issue with this component, so maybe it's a good chance to figure it out.

**Comment by jasonslyvia** [comment]
The css url provided is not reachable, can you provide a working fiddle or snippet so I can debug it?

**Comment by sdmgeek** [comment]
The css file is the below one.
github doesn't support uploading .css file here, so I renamed it to .txt. Just download and rename it back to .css, then add it to a lazyload working page as a link tag.

[grommet.min.txt](https://github.com/jasonslyvia/react-lazyload/files/329245/grommet.min.txt)

**Comment by jasonslyvia** [comment]
interesting, it's related to #30  and #31 , because your css add `overflow` props for `html`, and `react-lazyload` recognize this as a `overflow` mode.

maybe a solid `overflow` mode check is nedded.

**Comment by sdmgeek** [comment]
really appreciate for your help!

**Comment by jasonslyvia** [comment]
I have a quick fix for your problem in case you are urgent to use, `2.1.3` should work fine. But for long term solution, I should look into #31  and try to find more solid way.
