### ISSUE TITLE
The issue in checkOverflowVisible

### ISSUE THREAD

**Issue by SickSAMA** [jasonslyvia/react-lazyload#33]
```checkOverflowVisible``` currently is used if the lazyload component is scrolled in an element. In the function I figured that the element's top is calculated using ```offsetTop```
```javascript
  const elementTop = node.offsetTop;
  const elementBottom = elementTop + elementHeight;
```
```offsetTop``` returns the distance of the current element relative to the top of the ```offsetParent``` node. So the ```offsetTop``` is not the correct top if the ```offsetParent``` is not the ````scrollParent```.

I recommend just use ```getBoundingClientRect``` to check the visibility of the element. In the ```checkNormalVisible``` function 
```javascript
  const { top, height: elementHeight } = node.getBoundingClientRect();
  const elementTop = top + scrollTop; // element top relative to document
  const elementBottom = elementTop + elementHeight;

  const windowInnerHeight = window.innerHeight || document.documentElement.clientHeight;
  const documentBottom = scrollTop + windowInnerHeight;

  const offsets = Array.isArray(component.props.offset) ?
                component.props.offset :
                [component.props.offset, component.props.offset]; // Be compatible with previous API

  return (elementTop - offsets[0] <= documentBottom) &&
         (elementBottom + offsets[1] >= scrollTop);
```
you can just remove the scrollTop because
```javascript 
    elementTop - offset[0] <= documentBottom
--> top + scrollTop - offset[0] <= scrollTop + windowInnerHeight
--> top - offset[0] <= windowInnerHeight

    elementBottom + offsets[1] >= scrollTop
--> scrollTop + windowInnerHeight + offsets[1] >= scrollTop
--> windowInnerHeight + offsets[1] >= 0
```

For the overflow situation, just check the whether the element is in the intersection of its scrollParent and viewport.

**Comment by flyfy1** [comment]
I'm curious about this solution.. @jasonslyvia any comments..?
