### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by bryancr89** [jasonslyvia/react-lazyload#34]
I'm using the version 42.0 of Firefox for Mac and the lazyload doesn't work well

**Comment by jasonslyvia** [comment]
By not work well do you mean there is not lazy load effect at all, or any other issue? Which version of `react-lazyload` are you using? Is there any console error? Can you share some snippets how you're using this library?  

This might help debugging.

**Comment by jasonslyvia** [comment]
closing for no further information provided.

**Comment by MartinGao** [comment]
Same problem here.
I tried 2.1.0 - 2.1.6 but seems like none of them work.
There was no console error as far as I could notice.
I used react-lazyload with placeholders. 
In Chrome it worked as expected and placeholders were replaced by actual contents when scroll down. 
In Firefox, placeholders were there forever and no content was showen.

**Comment by jasonslyvia** [comment]
Is the demo working for you on Firefox? Which exact version of Firefox are you using? OS version appreciated too.
