### ISSUE TITLE
Overflow-x:hidden on html brakes lazy loading 

### ISSUE THREAD

**Issue by chrismadrigal** [jasonslyvia/react-lazyload#35]
I ran into an issue where the `<html>` and `<body>` had `overflow-x:hidden` because of this slider menu plugin we are using, this was causing lazy load to break when scrolling vertically.

Not sure if it is by design but I thought I'll mentioned here. It may also be related to #33

**Comment by jasonslyvia** [comment]
Which version are you using? Have you tried the latest version?

**Comment by MartinGao** [comment]
This also happend to me. I am using Semantic-ui which also has "overflow-x:hidden" by default.
I was using 2.1.6 at the beginning but failed as @chrismadrigal described.
Then, I tried previous versions one by one and magically 2.1.3 worked.
The 2.1.4 udpate might change somehting related to this issue.

**Comment by jasonslyvia** [comment]
Weirder and weirder, I'll dig it.

**Comment by pokka** [comment]
got this too... Weirder

**Comment by jasonslyvia** [comment]
hey guys, please try `2.2.1` and let me know if it solves this issue, thx.

**Comment by BlueXiphoid** [comment]
I use version `2.2.3` and it works for me, just to confirm.

**Comment by jasonslyvia** [comment]
Cool, I'm closing this issue for now, feel free to reopen it if it doesn't work for you.

**Comment by dcurletti** [comment]
In version `2.3.0` this is still an issue.  

Semantic UI's pusher element has `overflow-x:hidden` on it and it breaks the lazy loading as previously mentioned in the comments.

**Comment by binary64** [comment]
Same issue here with ant.design's <Layout>

**Comment by andremw** [comment]
Same here

**Comment by ameerthehacker** [comment]
@binary64 @andremw @dcurletti anyone of you can you provide a minimal example in codepen or jsbin!
