### ISSUE TITLE
Reverse direction?

### ISSUE THREAD

**Issue by uneart** [jasonslyvia/react-lazyload#36]
I am using react-lazyload within an overflow container for chat messages (newest messages at the very bottom). Is it possible to reverse the direction, so start at the very bottom, scroll upwards and lazy load those items?

**Comment by jasonslyvia** [comment]
It's possible, try set `offsets` props as an Array, and first element of that array represents the top end offset, the second represents the bottom end offset, pass a negative value as the second element might do want you want.

P.S. There is another library called `react-lazy-load` does the same job as `react-lazyload`, be aware of which one you are using 😉

**Comment by uneart** [comment]
Thank you, I totally overlooked the ability to set offset as an array in the docs. It works perfectly now with just setting scrollTop of the container to its height on initial mount.

P.S.: Corrected my little typo 😉

**Comment by jasonslyvia** [comment]
Glad it works, cheers!

**Comment by Afelua** [comment]
So, the main example will be:

`
const App = () => {
  return (
    <div className="list">
      <LazyLoad height={1000}>
        <img src="tiger.jpg" /> /*
                                  Lazy loading images is supported out of box,
                                  no extra config needed, set `height` for better
                                  experience
                                 */
      </LazyLoad>
      <LazyLoad height={200} once offset={-100} >        
                                /* Once this component is loaded, LazyLoad will
                                 not care about it anymore, set this to `true`
                                 if you're concerned about improving performance */
        <MyComponent />
      </LazyLoad>
      <LazyLoad height={200} offset={-100}>
                              /* This component will be loaded when it's top
                                 edge is 100px from viewport. It's useful to
                                 make user ignorant about lazy load effect. */
        <MyComponent />
      </LazyLoad>
      <LazyLoad>
        <MyComponent />
      </LazyLoad>
    </div>
  );
};`


Yes, it's ok?

**Comment by jasonslyvia** [comment]
It depends on your needs, just pull the demo and fiddle with it 😉

**Comment by Afelua** [comment]
So, please, tell me, where is demo with reverse direction?

**Comment by jasonslyvia** [comment]
@Afelua Hmm, you can clone `git@github.com:jasonslyvia/react-lazyload.git` and do a `npm install`, run `npm run demo:watch`, then open your browser and type `127.0.0.1:8721`, you will see the demo up and running.

Then try change the code in `examples/`, the demo will be recompiled on the fly, until you find out the result.

**Comment by JinJieTan** [comment]
But I have not solved this problem, do you have a specific solution
