### ISSUE TITLE
关于 2.4.1 改动的疑问

### ISSUE THREAD

**Issue by pokka** [jasonslyvia/react-lazyload#38]
看了新版本(2.4.1)的代码, 似乎不再需要同时声明 `height` 和 `placeholder`, [相关代码](https://github.com/jasonslyvia/react-lazyload/commit/8508ada96e9eb732c472c39dded79019459703d3#diff-6d186b954a58d5bb740f73d84fe39073L245)

对比之前版本的实现方法, 发现的确不再需要直接关心这个数值(其实以前也不是直接根据他来判断, 不知道理解错没); 

由于对实现不全理解, 可不可以简单的认为:
  1. 有了设定 `height` 的` placeholder` 后就不再需要设置组件的` height` 属性来` result better lazyload performance ` 
  2. 如果使用自定义的` placeholder`, 可以通过任意方式, 包括 css, style 的各种单位(如 em, px) 来定义它的 height, 这种做法不会导致比以前差的性能

谢谢

**Comment by jasonslyvia** [comment]
是的，你的理解完全正确。

react-lazyload 的工作方式就是在第一次 render 的时候不渲染真正的组件，而是渲染一个 placeholder，然后计算当前这个 placeholder 是否在整个页面中可见。

设想一个页面中全部都是 `<Lazyload>` 包裹的组件，如果 placeholder 没有一个合适的高度（甚至没有设置高度，offsetHeight 为 0），那么在 react-lazyload 在计算的时候就会认为这些组件当前都是可见的，就会把所有真实的组件渲染出来。

这就是 `height` 这个 props 的意义，需要你手动指定『这个模块被真实渲染出来后的高度』。

如果你设置了自定义的 placeholder，则需要你自己给这个 placeholder 添加合适的高度（通过 css 也好，style 属性也好）。

**Comment by pokka** [comment]
thx

**Comment by mqliutie** [comment]
可是我在2.2.4版本加入了 height 还是渲染除了真正的组件,如果不加入 placeholder 属性的话就不会渲染真实组件,渲染了一个 heigh={自定义} 高度的 div. 不知道怎么回事

**Comment by jasonslyvia** [comment]
@mqliutie 没太看懂你的问题，有必要的话新开一个 issue，把可以复现的代码贴上来。
