### ISSUE TITLE
node_modules/history included in tarball published on npm

### ISSUE THREAD

**Issue by callahanchris** [jasonslyvia/react-lazyload#43]
Just tried to run `npm shrinkwrap` on a project that includes `react-lazyload` as a dependency and got this error:

```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: history@2.1.1 /path/to/node_modules/react-lazyload/node_modules/history
```

[Here's a link](https://npmcdn.com/react-lazyload@2.1.4/node_modules/) to the module on npmcdn.

It seems like the issue with erroneously publishing the `history` module should be fixed in recent versions of npm -- see https://github.com/npm/npm/issues/9642.

**Comment by jasonslyvia** [comment]
That's weird, I'm building and publishing this package using `npm@3.6.0`, the referenced issue should have been fixed. Anything you suggest should I investigate in?

**Comment by callahanchris** [comment]
Looks like the issue for npm 3 was fixed in `npm@3.8.7` (https://github.com/yahoo/react-intl/pull/395#issuecomment-207217451). Just tried doing the following locally with node `6.4.0` and `npm@3.10.3`:

```
git clone git@github.com:jasonslyvia/react-lazyload.git
cd react-lazyload
npm install
npm pack
tar xzf react-lazyload-2.1.4.tgz
ls package/node_modules
```

and get the following message: `ls: package/node_modules: No such file or directory`

**Comment by jasonslyvia** [comment]
Cool, I'll update ASAP.

**Comment by callahanchris** [comment]
@jasonslyvia any update on this? Just upgraded to `react-lazyload@2.1.5` and the `node_modules` folder is still included: https://unpkg.com/react-lazyload@2.1.5/node_modules/

**Comment by jasonslyvia** [comment]
I sorry it has been delayed, could you please try `2.1.6`?

**Comment by callahanchris** [comment]
awesome, thanks for pushing that up!

**Comment by jasonslyvia** [comment]
Cheers, thanks for your patience.
