### ISSUE TITLE
Can we cut a new release?

### ISSUE THREAD

**Issue by lidawang** [jasonslyvia/react-lazyload#47]
Hello! I'm sorry for being spammy, but we'd really like to get this fix https://github.com/jasonslyvia/react-lazyload/pull/41 into our environment to fix the bug it was causing for us.

**Comment by jasonslyvia** [comment]
Sure thing, `2.1.5` it is.

Btw, would you like to collaborate on this repo, I'm kinda busy these days, expecting a helping hand here.

**Comment by lidawang** [comment]
Sure! I'd be happy to help out :)

**Comment by jasonslyvia** [comment]
Really appreciated!
