### ISSUE TITLE
parent.getAttribute is not a function error

### ISSUE THREAD

**Issue by cnolimit** [jasonslyvia/react-lazyload#48]
After debugging this issue i have come to find that `parent` variable is being set to either Window or Document but neither of the two contain the `getAttribute()` function.

This issue breaks my code and prevents the render of the component. I have defined my `LazyLoad` component as so..

```
    <div className={'Section6')}>
      <LazyLoad height={333} offset={300} overflow once>
        <Picture
          image={sectionImage}
          imageRetina={sectionImageRetina}
          imageMobile={sectionImageMobile}
          imageMobileRetina={sectionImage}
          screen={SCREEN_SIZES.SCREEN_SM_MAX} />
      </LazyLoad>
    </div>
```

The parent div has a `position: relative;` styling 

Have I not used the overflow prop correctly? because it seems that although the overflow prop os set, the returned object in parent doesn't contain the function which needs to be checked for the condition and therefore breaks at this point and throws an error.

![alt text](https://s22.postimg.org/r6wj6z8xt/Screen_Shot_2016_09_13_at_16_34_56.png"react-lazyload/src/index.js")

Have i missed something?

**Comment by jasonslyvia** [comment]
If you use `overflow` props, you have to make sure there's `overflow: auto;` or `overflow: scroll;` set on `<LazyLoad>`'s parent, technically it could be `html`, but in that way you don't have to use `overflow` at all.

**Comment by cnolimit** [comment]
I applied `overflow: auto` across all the sections which has allowed the `<LazyLoad>` to behaviour as it should, only i've come across an edge case whereby I have an image within the section which overflows but once `overlow: auto` or `overflow: scroll` is applied the image is then clipped but without the overflow styling the image will not be lazy loaded.

In this case, is there another way I should be handling this particular section?

**Comment by jasonslyvia** [comment]
If ancestor hasn't got `overflow: auto;` or `overflow: scroll;`, you shouldn't add `overflow` props to `<Lazyload>`.

**Comment by jasonslyvia** [comment]
Do you change `overflow` style of LazyLoad's ancestor on the fly?

**Comment by cnolimit** [comment]
no, there not changed on the fly, the ancestor did have overflow: auto, so i removed the `overflow` prop from the `<LazyLoad>`, but now the image is clipped, this illustration might help to visualise the issue i'm having.

![alt text](https://s21.postimg.org/iw0ukvg7b/Screen_Shot_2016_09_19_at_12_46_54.png "Overflow Issue")

**Comment by kalgm** [comment]
I had a work-around for this issue. Note that if you are setting overflow on your outer div through css, it is possible that the CSS is applied _after_ the LazyLoad processes your div. It will therefore bubble up each parent until it reaches the root document.

I solved this with inline styles on my overflow component.

`
  render() {
    var overflowStyle = {
      'overflowY': 'auto',
      'overflowX': 'hidden'
    }

    return(
      <div className={theme.studentList} style={overflowStyle}>
      { populateWithLazyLoad components }
      </div>
   )
}
`

**Comment by yangg** [comment]
I had the following structure
```jsx
<overflow container>
    <container>
      <lazyload overflow={true}><img...
   </...>
</...>
```
When I try to remove the container element, this error occus:
```
Uncaught TypeError: parent.getAttribute is not a function
```

**Comment by jasonslyvia** [comment]
hi @yangg , can you post your css on `overflow container` and `container`?  I believe there is something wrong introduced by another bugfix.

**Comment by yangg** [comment]
this is style of my overflow container
```
{
    width: 377px;
    background-color: #fff;
    overflow: auto;
}
```
the container has no styles currently.

**Comment by jasonslyvia** [comment]
I assume you're using `react-lazyload@2.2.1`?

**Comment by yangg** [comment]
@jasonslyvia  I've updated to 2.2.1, same error occurs.

**Comment by jasonslyvia** [comment]
Can you please try `2.2.2`?

**Comment by yangg** [comment]
@jasonslyvia  It works now.

**Comment by jasonslyvia** [comment]
hi @cnolimit , can you please try version `2.2.2` to checkout if it solves your issue?

**Comment by cnolimit** [comment]
hi @jasonslyvia and @yangg  thanks for all your help, although since posting this issue i've changed the structure of the code and so i'm unable to check whether these solutions would work for me. but since refactoring I haven't ran into any errors and found it works much better now.
