### ISSUE TITLE
Lazy load not rendering components when list is reversed

### ISSUE THREAD

**Issue by grahamtallen** [jasonslyvia/react-lazyload#53]
It seems that when you reverse the list that lazyload is rendering, it does not detect the change, so the items that were on the bottom of the list that are now at the top are not loading at all.

**Comment by jasonslyvia** [comment]
You can import `forceCheck` like `import { forceCheck } from 'react-lazyload';` and invoke this method whenever you made some changes.

**Comment by jasonslyvia** [comment]
It's undocumented feature, maybe I should add some docs :p

https://github.com/jasonslyvia/react-lazyload/blob/7b282db4f811871c43d31d2e1e81c7e387210abd/src/index.js#L272

**Comment by grahamtallen** [comment]
Thanks @jasonslyvia ! That works seemlessly, we are calling forceCheck in the componentWillUpdate() function. I can provide more details to our implementation if you want.
