### ISSUE TITLE
Render component if at top on load

### ISSUE THREAD

**Issue by NeXTs** [jasonslyvia/react-lazyload#55]
Plugin doesn't handle case when lazyloaded element is already positioned in viewport on page load (at the top of the page).
It requires at least one scroll event to occur.

**Comment by jasonslyvia** [comment]
In `componentDidMount`, there's a `checkVisible` call, so it should work just fine.

https://github.com/jasonslyvia/react-lazyload/blob/7b282db4f811871c43d31d2e1e81c7e387210abd/src/index.js#L207

Maybe some demo code which reproduces this issue will help.

**Comment by NeXTs** [comment]
my bad, everything is fine
