### ISSUE TITLE
How to use this with an rest api?

### ISSUE THREAD

**Issue by pcegarra** [jasonslyvia/react-lazyload#58]
I need to display a list view with more than 1000 elements, so I need to load the data from 20 to 20.
Can you post an example loading async data with an api rest?
Or any suggest please?

**Comment by jasonslyvia** [comment]
In your case I don't even think you need this library at all, is rendering 20 elements at a time still resource expensive?

**Comment by pcegarra** [comment]
mmm no, I want to display a lazy load list with scroll, loading items progressive..

**Comment by jasonslyvia** [comment]
I'm afraid that you have to implement this feature by yourself, here's some pseudo code:

```javascript
class Component extends React.Component {
  list = [];

  handleScroll() {
    // determine if it's end of the list,
    // if so, send request and load more data
    fetch('/api/xxx.json')
    .then(res => res.json())
    .then(data => {
      this.setState({
        list: this.state.list.concat(data);
      });
    });
  }

  render() {
    return (
      <div className="list" onScroll={::this.handleScroll}>
        {list.map((item, i) => <div key={i}>{item.name}</div>)}
      </div>
    );
  }
}
```

**Comment by pcegarra** [comment]
Why are you afraid?xD then, this library isnt for load dynamically data?

**Comment by jasonslyvia** [comment]
No, it's no lazy rendering a React component.
