### ISSUE TITLE
parent.scrollTop() not a function

### ISSUE THREAD

**Issue by ENDiGo** [jasonslyvia/react-lazyload#6]
in this line https://github.com/jasonslyvia/react-lazyload/blob/master/src/index.js#L24

'parent' hasn't own scrollTop() function.

**Comment by jasonslyvia** [comment]
Oops, it should be `parent.scrollTop` instead of a function call, jQuery ruins me. 

Will be fixed soon, thanks!

**Comment by jasonslyvia** [comment]
Fixed in 16ef39e5047fe7c6737cb116aefd9f533ff0a472
