### ISSUE TITLE
unmountIfInvisible not working

### ISSUE THREAD

**Issue by pcegarra** [jasonslyvia/react-lazyload#61]
Hi,
Im using this library to hide charts in the dom, but never dissapears

`LazyLoad unmountIfInvisible={true} height={600}
`

**Comment by jasonslyvia** [comment]
This feature had not been published, please try `2.2.0`.

**Comment by pcegarra** [comment]
can u upload it to npm?

**Comment by pcegarra** [comment]
Sorry, I dont remember how to use this library  😅
