### ISSUE TITLE
when use react-iscroll , react-lazyload is not work ?

### ISSUE THREAD

**Issue by webliving** [jasonslyvia/react-lazyload#62]
when use react-iscroll , react-lazyload is not work ?

**Comment by jasonslyvia** [comment]
Maybe `react-iscroll` is interfering with `scroll` event, if this library provide some kind of `onScroll` callback, you can pass `forceCheck` from `react-lazyload` to manually do the checking.

**Comment by webliving** [comment]
Yes, I've found it. I'll try it later. 😄

**Comment by jasonslyvia** [comment]
closed for no further update

**Comment by gyx8899** [comment]
Hi @jasonslyvia ,
I have tried with "forceCheck", it worked. But there will be two warnings:

> Warning: Browse is accessing findDOMNode inside its render(). render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.

> Warning: Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

And I find "findDOMNode" in "react-lazyload/libs/index.js" line-157.
Please help have a check.  Thanks.

`
import ReactIScroll from 'react-iscroll';
import iScroll from 'iscroll/build/iscroll-probe';
import {forceCheck} from 'react-lazyload';
`
`<ReactIScroll ref={this.listScroll}
		        onScroll={forceCheck()}
			iScroll={iScroll}>
	<ul className="list-container">
		{listDom}
	</ul>
</ReactIScroll>`

**Comment by jasonslyvia** [comment]
@gyx8899  instead of `onScroll={forceCheck()}` you should just pass `onScroll={forceCheck}`, that way prevents `forceCheck` being called during `render`

**Comment by gyx8899** [comment]
@jasonslyvia , thank you for your reply.
But LazyLoad doesn't work when just pass `onScroll={forceCheck}`.
The placeholder is always in there.
`<div class="lazyload-placeholder" style="height: 312px;"></div>`

**Comment by jasonslyvia** [comment]
@gyx8899 maybe you should open a new issue with reproducible snippets so I can dive into
