### ISSUE TITLE
unmountIfInvisible causes unwanted behaviour

### ISSUE THREAD

**Issue by davidtzoor** [jasonslyvia/react-lazyload#63]
First of all - amazing job!
I am using `react-lazyload` for a very big table and added the `unmountIfInvisible` option. My rows have an unknown height which is based on their content. When I scroll up and down the invisible lines are replaced with the `placeholder`, which is of a constant size. This causes the visible lines to "jump" up or down because of the height differences.
Is there any way to make each `placeholder` the same height as the component it replaces? or any other way to prevent this behaviour?
Thanks 😄

**Comment by jasonslyvia** [comment]
You can provide your own placeholder component and style its height as you like.

```jsx
<LazyLoad placeholder={<YourPlaceholder />}>
  <Row />
  <Row />
</LoadLoad>
```

**Comment by davidtzoor** [comment]
The children components have a dynamic height, which can be changed by user action. How can I give the Placeholder the height of the original component it replaces? It needs to be done somehow within the LazyLoad component.

**Comment by jasonslyvia** [comment]
Hmm, interesting, maybe `placeholder` can be a function, and you can do it like this:

```jsx
<LazyLoad placeholder={() => <YourPlaceholder style={{ height: getCustomHeight() }} />}>
  <Row />
  <Row />
</LoadLoad>
```

**Comment by davidtzoor** [comment]
That sounds like a good idea... Since I am creating the LazyLoad components in a loop (`map`) as to how to keep a reference of the inner component in the Placeholder creation function? Maybe give a unique id for each of the rendered component and then use `React-Dom` to locate it? (I don't really like this approach)

```jsx
function getCustomHeight() {
    // need InnerComponent's rendered height in time of placeholder creation...
}

{elements.map(el, index) => (
    <LazyLoad placeholder={() => <YourPlaceholder style={{ height: getCustomHeight() }} />} 
        <InnerComponent />
    </LoadLoad>
)}
```

**Comment by jasonslyvia** [comment]
I believe this is the business logic you have to deal with, after all, there is no way to track the change of height of your component.

**Comment by jasonslyvia** [comment]
closed for no further update
