### ISSUE TITLE
How to use it with typescript

### ISSUE THREAD

**Issue by hackereg35** [jasonslyvia/react-lazyload#64]
I can't use it with typescript i get this error
error TS7016: Could not find a declaration file for module 'react-lazyload'
i can't find a declaration ".d.ts" file on github.com/DefinitelyTyped/DefinitelyTyped

**Comment by jasonslyvia** [comment]
I'm sorry but this library didn't come up with a `.d.ts` file, but I believe you can just use `react-lazyload` without typings just fine.

**Comment by hackereg35** [comment]
I get the error above

**Comment by jasonslyvia** [comment]
I'm not quite familiar with typescript, but can you try `import LazyLoad from 'react-lazyload';` ?

**Comment by layershifter** [comment]
@jasonslyvia is right, use `import LazyLoad from 'react-lazyload'`.

**Comment by hackereg35** [comment]
i had to ignore the "any type" error and set the allowJS flag to true

**Comment by prchando** [comment]
@hackereg35 what did worked finally
something 
const lazyLoad: any = require('react-lazy-load'); // tslint:disable-line:no-any variable-name

or 
import LazyLoad from 'react-lazy-load'; // tslint:disable-line:no-any variable-name

The first one compiles for me but then it fails eventually.

Also is there a test page I can check how it works. The example page provided is not sufficient for the demo
