### ISSUE TITLE
Image does not render until scroll stops on the lazyloader element

### ISSUE THREAD

**Issue by prchando** [jasonslyvia/react-lazyload#66]
I found a serious bug with the lazy loader where sometime images will never load until someone explicitly stops scroll to the view which can trigger lazy loader to load images.

Assume there is a page with mix of images and text. 
So if you quickly scroll through the page to the bottom (with multiple images still in lazy load state), with default debounce, you will reach to the bottom of the page but page still has not loaded the image. 
This gives user a impression that page is small (without images), expect you implement some placeholder.
If user again scrolls to the top, will not find any image on the way. When you release scroll at the top, lazyload image is not in the viewport hence it will not load. 
Trick is you know there is a image in the page, and you scroll to that location and stop scrolling, suddenly image pops up. 

I think the logic should be to trigger loading all the lazy resources which has passed through the view, not just where scroll stopped. This is a serious bug to be fixed

**Comment by prchando** [comment]
Well if I use throttling, then also same issue will occur but in a different measure

It is important to render elements from top to bottom to avoid flicking experiece of the page

**Comment by jasonslyvia** [comment]
Hi @prchando , I believe there are 2 ways to solve this issue:

1. pass `debounce={false} throttle={false}` to disable all delay function, but it's not recommended because you might suffer from frequent updates and maybe visual lags
2. set appropriate `height` props for **every lazy loaded images**, doing this ensures that when users scroll down, while the image is not loaded, the place it will occupy is rendered, so no more flicking.

```jsx
<LazyLoad height={300}>
  <img src="my-cat.png" width={200} height={300} />
</LazyLoad>
```

**Comment by prchando** [comment]
@jasonslyvia Well contents are dynamic in nature, you never know the height based on the dynamic data or different image. 
For responsive image (<Picture>), it even becomes more difficult.

**Comment by prchando** [comment]
@jasonslyvia It would be also optimum to provide a hook for loading the resources not only when user scroll but when it is idle. So essentially while we can render page fast without rendering hidden parts, it is good to load hidden parts proactively before scroll, if it is idle

**Comment by jasonslyvia** [comment]
I'm afraid without a well-assumed height for your lazy loaded component, it would be tough to 'lazy load' them.

Imagine a document populated with lazy loaded component, at the first render, the document is blank, which means the document has no height, how can you determine if the lazy loaded components should become visible?

It would be possible to render them one by one, and check viewport size change and visibility after each one rendered, but it's over optimized and will cause much more rendering.

**Comment by prchando** [comment]
@jasonslyvia I tried with placeholder and that makes things better with original problem. Thanks
You can close this topic

**Comment by jasonslyvia** [comment]
Glad you work it out, btw, placeholder is another way to set `height`, but by CSS not props.
