### ISSUE TITLE
Works within only one bundle

### ISSUE THREAD

**Issue by prchando** [jasonslyvia/react-lazyload#68]
It stops working when imported into multiple bundles. Only one of it works.
I debug and the reason is only one of the instance receive window.scroll event, others does not receive. Which one receives depends on race condition. I can see one copy of LazyLoad in each bundle

I think you can repro this using two separate react components in two files and lazy loading both

**Comment by prchando** [comment]
I think I got where this problem is coming from
var listenerCount = 1 + +parent.getAttribute(LISTEN_FLAG);
if (listenerCount === 1) {
	parent.addEventListener('scroll', finalLazyLoadHandler);
}
This logic break when multiple bundle are updating same flag. 
I think you can use some more robust logic within code rather updating parent's attribute 
One way could be checking the count of Listener and add listener when first time (listeners empty)
remove listener when none of it remains in the listeners

**Comment by jasonslyvia** [comment]
Interesting, can I assume you actually load two `react-lazyload` library into the same document?

**Comment by jasonslyvia** [comment]
Closed for no further information.
