### ISSUE TITLE
About dynamic src

### ISSUE THREAD

**Issue by NE-SmallTown** [jasonslyvia/react-lazyload#69]
In my project,I need load the image src dynamic because it's responsive.

For example,I want to load big img in PC and small img in Phone,so I wish I can use something like 
```
onLoad(e) => {
    e.target.src = 'http://www.cdn.images.mySite.com/someImage.jpg?width=e.target.width&height=e.target.height';
}
```

But I find that React(I am not sure, maybe this respo?) has added load event on image,so therer is a conflict.Are there some good ways to resolve this?If you have,please tell me,thanks a lot!

**Comment by jasonslyvia** [comment]
Neither React nor react-lazyload has interfered with image's `load` event, if you like, you can provide some code snippets so we can dig it.

**Comment by NE-SmallTown** [comment]
@jasonslyvia 
You can see this in [examples of this repo](http://jasonslyvia.github.io/react-lazyload/examples/#/image):

![](http://www.blog.ne-smalltown.com/commonUpload/2017-01-09_17-02-36.jpg)

**Comment by jasonslyvia** [comment]
The reason why you can see the `load` event listener is React listen all kinds of event on top level elements, it doesn't mean React has done anything for `img`, unless you explicitly use `<img src="xxx.jpg" onLoad={handleLoadImage} />`.

**Comment by NE-SmallTown** [comment]
@jasonslyvia oh,god,I forget that it seems like `on` or `delegate` in `JQuery`.Thanks,
