### ISSUE TITLE
Does not work in overflow container on iOS Safari

### ISSUE THREAD

**Issue by rayshan** [jasonslyvia/react-lazyload#7]
Hello,

I haven't tried all mobile devices yet, just did a quick test on an iPad Mini 1 / iOS 9.2 Safari. The demo loads but scrolling to the bottom with finger doesn't trigger content loading. I'm guessing wheel events aren't fired in this environment.

The normal demo works as expected in this environment.

**Comment by rayshan** [comment]
Also scrolling is janky in the overflow container. Not sure if it's caused by this library. Scrolling is smooth in normal demo.

**Comment by jasonslyvia** [comment]
Fixed in `1.6.1`, please try this [demo](https://jasonslyvia.github.io/react-lazyload/examples/#/overflow?_k=9rcnaq).

**Comment by rayshan** [comment]
Working now, thanks!
