### ISSUE TITLE
scrollParent方法中的一个正则判断可能会出问题

### ISSUE THREAD

**Issue by pasturn** [jasonslyvia/react-lazyload#71]
### scrollParent.js
```
.....
 if (overflowRegex.test(overflow + overflowX + overflowY)) {
      return parent;
    }
....
```
场景：
当body设置overflowX或者overflowY其中一个为非scroll或auto的时候（如：overflowX:hidden），overflow和另外一个会自动设置为auto，则会导致这个正则判断为真，直接输出body为parent，这样就会导致isOverflow判断为真，可视范围以外的图片就会无法显示
### index.js
```
const checkVisible = function checkVisible(component) {
...
 const isOverflow = parent !== node.ownerDocument &&
                     parent !== document &&
                     parent !== document.documentElement;
...
}

```

**Comment by jasonslyvia** [comment]
确实，详细的解释在此：  http://stackoverflow.com/a/6433475/761124 。

看来我们需要一个更通用的方法判断 scrollParent，不知道你有没有什么好的建议？

**Comment by pasturn** [comment]
```
   if (overflowRegex.test(overflow) && overflowRegex.test(overflowX) && overflowRegex.test(overflowY)) {
      return parent;
    }
```
临时用了一个判断来解决我这里遇到的问题

**Comment by jasonslyvia** [comment]
或许可以参考一下 jQueryUI 中 `.scrollParent()` 的判断方法 https://github.com/jquery/jquery-ui/blob/89af4c292eaa5fc1c83437ca71085264dcbef34a/ui/scroll-parent.js

**Comment by jasonslyvia** [comment]
已发布 `2.2.1` 修复该问题，对应的测试[在此](https://github.com/jasonslyvia/react-lazyload/blob/8b581908dd5ed08af3d7752c2e00b1e185bc3f38/test/specs/lazyload.spec.js#L287)，再次感谢反馈！

**Comment by thonglh** [comment]
@jasonslyvia I think it should not be counted as a bug this case.
When you set `overflow-x: hidden` and not set `overflow-y`, the `overflow-y` will be computed as `auto`, this is expected. And the last element will not be rendered is correct.

Please take a look here: https://jsfiddle.net/hcbxhny5/9/ 
(I built this base on your last spec, the `treasure` will be rendered when `fakeOverflowContainer` get scrolled )
I think we should revert to old `scrollParent` as **jqueryUI** version
