### ISSUE TITLE
onLoad property

### ISSUE THREAD

**Issue by tauren** [jasonslyvia/react-lazyload#73]
Would it be possible to add an `onLoad` property that accepts a function? This function would be called when the lazily loaded component is loaded.

My app keeps track of how many items you have not "seen" yet. As you scroll and these items come into view and are loaded, I'd like to mark them as having been "seen".

There are ways I can work around the lack of this feature, but it seems like it might be useful for others as well.

**Comment by lidawang** [comment]
You can do the tracking logic in your lazily-loaded component's `componentDidMount` method, as that will only be called once the component is loaded.

**Comment by tauren** [comment]
@lidawang That's what I meant by working around the lack of this feature. 

However, I don't have control over all of my lazily-loaded components. Of course, I can write a wrapping component or an HOC, but then I'm adding the logic to all of the various components that `<LazyLoad>` is loading. It seems the most DRY solution would be an `onLoad` in `<LazyLoad>` itself. 

If there is no interest in adding this, let me know and I'll close this issue.

**Comment by jasonslyvia** [comment]
I think adding a wrapper component for your need is sufficient, another `onLoad` may confuses user with the difference from `componentDidMount`.

**Comment by jasonslyvia** [comment]
I'm closing this for now, feel free to contribute ;-)
