### ISSUE TITLE
Placeholder component still visible

### ISSUE THREAD

**Issue by simofacc** [jasonslyvia/react-lazyload#74]
Hi,

I am using the lazy load component and I have a problem on mobile where after scrolling the placeholders are not updated.

I have the below overflows set in some of the top parents.

`
overflow-x:hidden;
overflow-y: auto;
`

If I tap on the placeholder it updates and shows the element correctly.

The LazyLoad component is as follows:

`
<LazyLoad
                    key={index}
                    height={156}
                    offset={156 * 3}
                    placeholder={<ListItemPlaceholder/>}
                    debounce={false} throttle={false}
                    unmountIfInvisible={true}
                    overflow={true}
                >
`

Any advice?

**Comment by jasonslyvia** [comment]
Can you provide some environment info? It will help me reproduce this issue. 
Such as which mobile platform, browser, Lazyload version, etc.

**Comment by simofacc** [comment]
Hi.

So I am testing on iOS 10.2 using the stock Safari browser with Lazyload 2.2.4.

I also tried on desktop chrome with the device responsive emulation.

**Comment by jasonslyvia** [comment]
Thanks @simofacc , I'll try to reproduce this issue.

**Comment by simofacc** [comment]
@jasonslyvia I managed to find the issue with the delay.

We had a scroll event listener and it was screwing up the lazy loading.

`document.addEventListener('scroll', _.throttle(scrollEventHandler, 16), true);`

So I added the forceCheck function inside that event handler and issue is solved. Somehow on desktop the issue was not so visible.

**Comment by jasonslyvia** [comment]
Can I assume you called `event.stopPropagation()` in your own scroll event handler?

**Comment by simofacc** [comment]
`
var scrollEventHandler = function (e) {
            if (pageElement && e.target === pageElement && previous > e.target.scrollTop) {
                Utils.scrollToTop();
            }
            previous = pageElement && pageElement.scrollTop;
            forceCheck();
        }
        document.addEventListener('scroll', _.throttle(scrollEventHandler, 100), true);`

No there is not much in the scroll event handler function.

**Comment by mqliutie** [comment]
`unmountIfInvisible`  在某元素不可见的时候没有 `unmount`

我的理解是如果这个元素不在视野之内,那么它应该会被替换成 `PlaceHolder` 的内容吧

但是我将 `unmountIfInvisible` 设置成` true` 的时候,那个元素不在可视区域内并没有替换成 `PlaceHolder` 内容

**Comment by mqliutie** [comment]
`!(component.props.once && component.visible)`

看了下代码, 原来 `once` 必须得设置成 `false` 才可以

**Comment by jasonslyvia** [comment]
@mqliutie `once` 意思就是一旦被懒加载的元素进入视口被渲染后，LazyLoad 就不再接管后续的事宜了，这里可能在文档中注明一下会更好。

**Comment by rodgobbi** [comment]
@jasonslyvia I'm having a similar problem.
It seems like the LazyLoad component isn't listening the scroll event from it's container (with overflow), and I need to force the check. Forcing the check causes it to work correctly but feels like not the natural behavior for me. The code is:
`<List className={cn(style.listaNotificacoes, className)} onScroll={forceCheck}>
        {notificacoes
          .map(notificacao =>
            <LazyLoad unmountIfInvisible overflow key={notificacao._OID} offset={[100, 100]} throttle={100} placeholder={<li className={style.placeholder}/>}>
              <ItemNotificacao
...`
List and ItemNotificacao have relative position, ItemNotificacao has the same height as <li className={style.placeholder}/>, List has overflow-y: auto.

This was supposed to not need the forcecheck, wasn't it?

**Comment by jasonslyvia** [comment]
@rodgobbi I guess it's because this line of code [https://github.com/jasonslyvia/react-lazyload/blob/7abb292f520756ee612ce862f4babdcd9d15eb1d/src/utils/scrollParent.js#L29](https://github.com/jasonslyvia/react-lazyload/blob/7abb292f520756ee612ce862f4babdcd9d15eb1d/src/utils/scrollParent.js#L29) , it is added for some weird overflow behaviour in Firefox, see #71  and [http://stackoverflow.com/a/6433475/761124](http://stackoverflow.com/a/6433475/761124).

**Comment by rodgobbi** [comment]
@jasonslyvia will I have similar performance if I set the scroll props to false and forceCheck in the scroll event of the parent compared to the scroll true working correctly?

**Comment by jasonslyvia** [comment]
Hmm, I'd suggest you stay using this hackish method till I find a stable `scrollParent` solution.

**Comment by nhlinhCS** [comment]
Hi all, I have this component fo Lazyload Image, when i scroll or stop scroll the placeholder still invisible. how to solve it?
`class LazyBackground extends React.Component {
  componentDidMount() {
    forceCheck();
  }

  render() {
    const { props } = this;
    return (
      <div className="lazy-image">
        <LazyLoad unmountIfInvisible={true} scroll={true} placeholder={props.placeholderContent}>
          <div>
            <CSSTransitionGroup
                transitionName='lazy'
                transitionEnterTimeout={1000}
                transitionLeaveTimeout={2000}
                transitionAppearTimeout={2000}
                transitionAppear={false}
              >
                {props.lazyContent}
              </CSSTransitionGroup>
            </div>
        </LazyLoad>
      </div>
    );
  }
}`
Thanks

**Comment by rodgobbi** [comment]
@nhlinhCS set prop onScroll={forceCheck} on the container component, that way `forceCheck` will be called every time the container is scrolled.

**Comment by nhlinhCS** [comment]
dear all, After trace my error, think, This code is work for me `overflow={true}` if your component is overlay and wrapped by parent element.
Thank @rodgobbi

**Comment by jasonslyvia** [comment]
@rodgobbi @nhlinhCS I don't recommend overusing `forceCheck` because it might be a potential performance issue.

**Comment by nhlinhCS** [comment]
@jasonslyvia, I just use `forceCheck` in `componentDidMout()`.

**Comment by Joelgullander** [comment]
Any updates on this?
