### ISSUE TITLE
'Server side rendering' support

### ISSUE THREAD

**Issue by sergei-zelinsky** [jasonslyvia/react-lazyload#76]
Hi, there.
What is about server side rendering?
Can you give me an example, please?
Thanks.

**Comment by jasonslyvia** [comment]
Good point, never considered about that. Maybe in the case of server side rendering, we should just render the children at once?

**Comment by sergei-zelinsky** [comment]
@jasonslyvia, thank you for your answer.
I am not sure if it is good idea. IMHO on the stage of server rendering we should not render anything. 
The first thought that came to my mind, is the following:
we should have a boolean property in our state which indicates if `lazyload` is enabled. Initially it should have `false` value. If `isLazyLoadEnabled` is `false` we don't render anything. Next in `componentDidMount` we set it to `true`, because lifecycle methods are called only on the client and we never have `isLazyLoadEnabled` with `true` value on the server.

**Comment by jasonslyvia** [comment]
If we render nothing, then current behaviour may just suit your need since in first round of rendering LazyLoad will render a placeholder no matter what. But for node-compatible concerns, we should check against some BOM object accessing.

**Comment by sergei-zelinsky** [comment]
@jasonslyvia 
Implementation is yours. I have just suggested an idea, because rendering all children of `LazyLoad` component on a server will cause loading of all images after browser loads a page.
For example:
```
<LazyLoad>
    <img src='http://example.com/some-src.jpg' />
</LazyLoad>
```

**Comment by Richacinas** [comment]
If I lazy load elements using this library and, being into the React world, the checksum of the server render and the client must be the same.... therefore, you should only load the first component rendered by the client. Is this true? how would this library go about "server side rendering"?

**Comment by jarzuaga** [comment]
Just fyi, I'm using this library for server side rendering "as-is" it works like a charm, just as @jasonslyvia mentions above.

**Comment by jasonslyvia** [comment]
@jarzuaga  Thanks for the confirmation, I believe we can assume this library is `SSR friendly`.

**Comment by bmxmaga** [comment]
Hi all. Sorry for digging out this issue but this library doesn't really work with SSR:

```
ReferenceError: window is not defined at LazyLoad.componentWillUnmount
```

For now, I've prepared a _workaround_ to overcome this problem but it would be nice if lazy load didn't throw the window error on server-side.

Here's my workaround:

```
import React from 'react';
import LazyLoad from 'react-lazyload';

export const UniversalLazyLoad = (props) => (
  typeof window !== 'undefined' ?
    <LazyLoad {...props}>{props.children}</LazyLoad> :
    <div className="lazyload-placeholder" style={{height: `${props.height}px`}}/>
);
```

If you don't care about markup match during hydration, then you're good to go with just `null` on server side.
Otherwise, you might need to populate the placeholder div element with more attributes. I'm using only `height` so the above example was sufficient for me.

**Comment by jasonslyvia** [comment]
@bmxmaga I'm wondering why will `componentWillUnmount` be called in SSR situation?

**Comment by bmxmaga** [comment]
You're right, that's interesting. But the fact is - it happened to me.
I didn't investigate further.

I'll get back with more info if I find any.

**Comment by manelgarcia** [comment]
I still always see the placeholder on SSR `v2.3`
May I be missing something? It's a custom implementation but I'm rendering twice due to api requests
