### ISSUE TITLE
IE11: Unspecified error (caused by getBoundingClientRect)

### ISSUE THREAD

**Issue by wub** [jasonslyvia/react-lazyload#77]
As explained here: https://github.com/dart-lang/sdk/issues/19065#issuecomment-108436331, IE soils the bed when it tries to `getBoundingClientRect` on an element not yet added to the document.

Is there any kind of check we could add to stop this happening? Does JS expose a way of checking if a node exists in the document yet?

**Comment by jasonslyvia** [comment]
Maybe just a `try...catch...` will do the trick?

**Comment by wub** [comment]
Nothing wrong with that IMO!

**Comment by jasonslyvia** [comment]
closed for #79
