### ISSUE TITLE
How To Set Default Image Holder

### ISSUE THREAD

**Issue by prakasa1904** [jasonslyvia/react-lazyload#78]
hi, i have some issue, I dont see/found where I can place default image if my image broken.

Please response,

reggards

Prakasa

**Comment by jasonslyvia** [comment]
I believe this is none of LazyLoad's concern, but I'd suggest you wrap your image in a `Image` component, and do the fallover stuff there.

```
class Img extends React.Component {
  state = {
    loading: true,
    error: false,
  };

  componentWillMount() {
    // load image and check if it's broken

    const img = new Image();
    img.onload = () => {
      this.setState({
        loading: false,
        error: false,
      });
    };
    img.src = this.props.src;
  }

  render() {
    // render a placeholder if `loading` or `error`
    // render a <img> otherwise
  }
}

React.render(<LazyLoad height={300}><Img src="xxx.jpg" /></LazyLoad>, node);
```

Please notice this is pseudo code and hasn't been tested;

**Comment by prakasa1904** [comment]
hhmmm, not sure that will help my problem or not, but thx. I hope developers add this feature :D

**Comment by prakasa1904** [comment]
I think I found what I need.. Please check here : https://github.com/jasonslyvia/react-lazyload/blob/master/examples/pages/placeholder.js

**Comment by jasonslyvia** [comment]
`placeholder` isn't meant for 'broken image substitution', rather it is just a placeholder for lazy-loaded component which just not being rendered. That said, when your image come to viewport, LazyLoad will just render your image, and if it's broken, you will see what normal `<img>` behave when image can't be loaded.

**Comment by jasonslyvia** [comment]
closing for no further updates.
