### ISSUE TITLE
Configuration of debounce

### ISSUE THREAD

**Issue by gavacho** [jasonslyvia/react-lazyload#8]
It would be nice to configure the debounce interval as well as choose between debouncing and throttling behavior.

**Comment by jasonslyvia** [comment]
These feature are implemented in `2.0.0-beta2` version, you can try it by `npm install -S react-lazyload@2.0.0-beta2`.

Docs and source are: https://github.com/jasonslyvia/react-lazyload/tree/2.0.0-beta2

Please let me know what you think of this.

**Comment by jasonslyvia** [comment]
It's supported for configuring `debounce` or `throttle` since `v1.6.0`, please checkout this [demo](https://jasonslyvia.github.io/react-lazyload/examples/#/throttle?_k=7mcjwu) and [docs](https://github.com/jasonslyvia/react-lazyload#debounce) for detail.
