### ISSUE TITLE
debounce option not working as documented

### ISSUE THREAD

**Issue by michaellopez** [jasonslyvia/react-lazyload#80]
Hi, reading the documentation it states that `debounce` option can be turned off by setting it to `false`, this is not true. You have to set it to `undefined`. [This line](https://github.com/jasonslyvia/react-lazyload/blob/master/src/index.jsx#L197) is looking for `undefined`, not `false`. Setting it to `false` set the default debounce value of `300`.

@jasonslyvia I'm willing to send a PR if you can let me know if I should adjust the documentation to match the code or vice versa?

**Comment by jasonslyvia** [comment]
Oh please send a PR to match this behaviour (set `false` to disable thing), ideally warn the user in the document that if they don't use either `throttle` nor `debounce` may suffer performance issue.

**Comment by jasonslyvia** [comment]
closing for no further updates
