### ISSUE TITLE
forceCheck doesnt load items that are already in viewport

### ISSUE THREAD

**Issue by constantx** [jasonslyvia/react-lazyload#83]
Current implementation:

```js
/**
*
* CoverPhoto
*
*/

import React from 'react';
import classnames from 'classnames/bind';
import DebugHelper from 'utils/debug';
import LazyLoad, { forceCheck } from 'react-lazyload';
import styles from './CoverPhoto.styl';

const cx = classnames.bind(styles);
const debug = new DebugHelper('components/CoverPhoto');

export class CoverPhoto extends React.Component {
  componentDidMount () {
    forceCheck();
  }

  render () {
// const CoverPhoto = (props) => {
    debug('render');
    const { props } = this;
    const className = cx(props.className, {
      coverPhoto: true,
      hasRatio: props.ratio,
      [`ratio-${props.ratio}`]: props.ratio,
    });
    const imgProps = {
      src: props.src,
      alt: props.alt,
    };

    return (
      <div className={className}>
        <LazyLoad
          height={props.height || 100}
          offset={300}
          once
        >
          <img
            {...imgProps}
            className={styles.photo}
            role="presentation"
          />
        </LazyLoad>
      </div>
    );
  }
}

export default CoverPhoto;
```

`CoverPhoto` is then used in other components, like a `ProductCard`:

<img width="222" alt="productcard" src="https://cloud.githubusercontent.com/assets/113969/24439043/f0f3797a-1475-11e7-8e07-932e2e51a700.png">

Though `forceCheck` is called, the image is not loaded even though ProductCard is already inside the viewport.

By looking at the log, somehow `componentDidMount` is being called before `render()`. Is that becuase the component is not fully mounted till `LazyLoad` finish rendering? Any hint on how this can be?

**Comment by jasonslyvia** [comment]
You don't need to call `forceCheck()` in this case, if your item(ie. `children` of LazyLoad) is already in viewport, LazyLoad will check its visibility in LazyLoad's `componentDidMount`, and if it's visible, LazyLoad will render your item.

I believe your issue here might have something with `offset` props, could you try removing `offset` and see what happens?

**Comment by constantx** [comment]
removed `offset`, still same behavior: as soon as I start scrolling, all the images load.

**Comment by constantx** [comment]
I can see the placeholder `div` (changed to `background:red` for visual guide here).

<img width="956" alt="developer_tools_-_http___localhost_5000_explore_and_chopp___sieu_th _t i_gia___1-hour_handpicked_groceries" src="https://cloud.githubusercontent.com/assets/113969/24499051/a37b8d5e-156a-11e7-82a0-e72414b4c09e.png">

And it's definitely above the viewport.

**Comment by constantx** [comment]
is the offset calculated based on the placeholder position during scroll?

**Comment by constantx** [comment]
it's odd, cause the photos for the slideshow above (the green part) above also use the same component, and the photo loads fine…

**Comment by jasonslyvia** [comment]
To be precise, `offset` is calculated based on placeholder's parent node, but its height is mostly depends on the placeholder's height, so we can agree on that one.

Is there a overview container(has a `overflow: auto` or `overflow: scroll` CSS property) for your images which have trouble with being lazy loaded?

**Comment by constantx** [comment]
So the lazy load part works no problem :) The issue is the one that is already in the viewport on first page load doesn't get loaded right away, but requires a scroll event to trigger.

![storefront-3](https://cloud.githubusercontent.com/assets/113969/24502089/7cce1e7c-1576-11e7-8122-4b1e63d169c1.gif)

All the images in that gif use LazyLoad, but the bigger one loaded right away, while the lower one needs a scroll event to trigger.

**Comment by jasonslyvia** [comment]
I can't conclude anything without debug your code, but I believe it is sort of involved with component mounting order and/or CSS, a dirty hack would be call `forceCheck` in your images' parent component's `componentDidMount`, it should do the trick.

**Comment by jasonslyvia** [comment]
Also, is your image list loaded asynchronously?

**Comment by constantx** [comment]
The image list is fetched after the main layout is rendered, data comes from another action.

<img width="1792" alt="developer_tools_-_http___localhost_5000_explore_and_chopp___sieu_th _t i_gia___1-hour_handpicked_groceries" src="https://cloud.githubusercontent.com/assets/113969/24537158/7697861c-160a-11e7-8033-c219028a856d.png">

<img width="1581" alt="developer_tools_-_http___localhost_5000_explore_and_chopp___sieu_th _t i_gia___1-hour_handpicked_groceries" src="https://cloud.githubusercontent.com/assets/113969/24537200/bdf98f0a-160a-11e7-9835-787663376110.png">

**Comment by constantx** [comment]
If possible, would love to jump on skype and get your help on this :)

**Comment by constantx** [comment]
cc @liemlyquan

**Comment by constantx** [comment]
@jasonslyvia I tried `forceCheck()` inside componentDidMount for the parent of the LazyLoaded component, but doesnt do anything.

**Comment by jasonslyvia** [comment]
By parent component I mean the component which renders your `CoverPhoto`.

**Comment by constantx** [comment]
> By parent component I mean the component which renders your CoverPhoto.

Ya, tried that too :(

```js
/**
*
* ProductCell
*
*/

import React from 'react';
import numeral from 'numeral';
import classnames from 'classnames/bind';
import { forceCheck } from 'react-lazyload';
// import { FormattedMessage } from 'react-intl';
import DebugHelper from 'utils/debug';
import { Col } from 'components/Grid';
import PriceTag from 'components/PriceTag';
import CoverPhoto from 'components/CoverPhoto';
// import messages from './messages';
import styles from './ProductCell.styl';

const debug = new DebugHelper('components/ProductCell');
const cx = classnames.bind(styles);

export class ProductCell extends React.Component {

  componentDidMount () {
    debug('componentDidMount');
    forceCheck();
  }

  render () {
    // debug('render', product);
    const {
      id,
      name,
      brand,
      price,
      origin,
      stores,
      unit,
      packaging,
      displayUnit,
      displayFactor,
    } = this.props;

    const className = cx({
      cell: true,
    });

    const thumbnail = this.props['thumbnail@2x'];
    const thumbnailUrl = thumbnail[0] && thumbnail[0].url;
    let displayPrice = price;
    let displayPackaging = packaging || unit;

    // set the correct display price
    if (displayFactor) {
      displayPrice = numeral(displayFactor).multiply(price);
      displayPackaging = displayUnit;
    }

    return (
      <div className={className}>
        <div className={styles.photoHolder}>
          <CoverPhoto height={146} src={thumbnailUrl} alt={name} />
        </div>
        <div className={styles.details}>
          <span className={styles.origin}>{origin || brand}</span>
          <h5 className={styles.name}>{name}</h5>
          <Col width={6} flushed>
            <PriceTag price={displayPrice} className={styles.price} />
          </Col>
          <Col width={6} flushed>
            <div className={styles.packaging}>
              <span className={styles.packagingContent}>{displayPackaging}</span>
            </div>
          </Col>
        </div>
      </div>
    );
  }
}

export default ProductCell;
```

**Comment by jasonslyvia** [comment]
Maybe in `componentDidUpdate`? Since I don't have an overview of your entire app, I have no idea when your `ProductCell` component will be mounted, if it is mounted before your image list fetched, you should try `componentDidUpdate`.

**Comment by constantx** [comment]
it seems like it has to do with the slides above the products block. When I remove the bigger image block above the grids, the products grid load fine. I suspect it has to do with the `react-slick` messing up with the viewport height…

**Comment by constantx** [comment]
so I found out why, but not sure how to fix it.

The slides above the product grids use react-slick, and apparently, when the both the ProductCell and react-slick component are mounted (`componentDidMount`), all the slides inside the react-slick momentarily got stacked vertically, and the `ProductCell` is technically below the viewport at this point, so regardless of how I call `forceCheck` inside the parents component, it still won't load. 

After this brief moment, the react-slick component has the correct height somehow, and the ProductCell is once again above the viewport.

Any tip? I've tried to do a `setTimeout(forceCheck, 1000)` but doesnt work still.

**Comment by constantx** [comment]
`setTimeout(forceCheck, 1000)` works ;)

**Comment by jasonslyvia** [comment]
Glad you work it out!

**Comment by joerlop** [comment]
@constantx Thanks a lot! Was having the same issue just now...
