### ISSUE TITLE
can't get scroll div in firefox when use overflow

### ISSUE THREAD

**Issue by 525729985** [jasonslyvia/react-lazyload#84]
getParent里的父级使用&&去判断是不是有问题?
//if (overflowRegex.test(overflow) && overflowRegex.test(overflowX) && overflowRegex.test(overflowY)) {
    if (overflowRegex.test(overflow) || overflowRegex.test(overflowX) || overflowRegex.test(overflowY)) {
      return parent;
    }

**Comment by jasonslyvia** [comment]
see #71 

如果确定是 Firefox 下的问题，麻烦提供一个可重现的代码片段

**Comment by 525729985** [comment]
/*scrollParent.js*/
console.log(parent.className + " " + overflowRegex.test(overflow)  + " " +  overflowRegex.test(overflowX) + " " + overflowRegex.test(overflowY));
/*css*/
.container{ overflow-y: scroll;}
最终在火狐下输出结果为container false true true,只有把overflow-y变成auto之后火狐才会正常

**Comment by jasonslyvia** [comment]
看来检测 scrollParent 还需要更精准的方案，这个我来跟进一下，感谢反馈。

2017-04-03 23:21 GMT+08:00 525729985 <notifications@github.com>:

**Comment by zemzheng** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=733295

我觉得直接判断 overflowRegex.test(overflowX) && overflowRegex.test(overflowY) ，忽略 overflow 比较合适吧。

**Comment by jasonslyvia** [comment]
all overflow and scrollParent issue have been moved to #129 , let's discuss there
