### ISSUE TITLE
lazy loading images requires a specialized component

### ISSUE THREAD

**Issue by gavacho** [jasonslyvia/react-lazyload#9]
I came to react-lazyload wanting to lazy load images.  It took a bit to figure out that I would need to create my own component which gets provided with a `visible` prop by `react-lazyload`.  My expectation was that the `LazyLoad` component wouldn't render its children if it weren't visible.

I did something like:

```
const LazyLoadImage = (props) => props.visible ? <img {...props} /> : <span {...props} />;

<LazyLoad once>
  <LazyLoadImage src="/example.jpg" style={{ display: 'block', width: 100: height: 100 }} />
</LazyLoad>
```

How are other people handling this use-case?

**Comment by jasonslyvia** [comment]
Sorry for the late response, kinda busy these days.

I've tweaked the code a little bit to render `null` for `once` set to `true` LazyLoad component when it is not visible.

Please try version 1.3.2 to see if it solves your problem.

**Comment by fredrikekelund** [comment]
I experienced the same issue with 1.3.2

**Comment by jasonslyvia** [comment]
Hi, sorry for the delay, `react-lazyload@1.5.0` is out, lazy loading images is supported out of box.

```javascript
<LazyLoad>
  <img src="tiger.jpg" height="200" />
</LazyLoad>
```

Or checkout the [demo](https://jasonslyvia.github.io/react-lazyload/examples/#/image) here.
