### ISSUE TITLE
package is broken due to prop-types change

### ISSUE THREAD

**Issue by bassjacob** [jasonslyvia/react-lazyload#92]
Hi :smile: 

see #91 

I can't use this package at the moment since one of it's requires is only declared as a devDep. PR #91 moves prop-types to be a dep instead, making the require work again.

**Comment by jasonslyvia** [comment]
Thanks, according to `prop-types` repo, this package should be listed as `dependency` indeed. 
`2.2.7` should work again, can you help confirm this?

**Comment by bassjacob** [comment]
hi @jasonslyvia, that all looks great to me. Thanks for such a quick turnaround on this!
