### ISSUE TITLE
Item inside overflow-container should be visitble when the document has scroll to show it

### ISSUE THREAD

**Issue by zemzheng** [jasonslyvia/react-lazyload#97]
```javascript
let firstHeight = window.innerHeight + 100;
ReactDOM.render(
  <div style={{ overflow: 'scroll' }} className="container">
    <LazyLoad height={ firstHeight } overflow><div style={{ height: `${ firstHeight }px` }} className="something">always can visited</div></LazyLoad>
    <LazyLoad height={220} overflow><div style={{ height: '220px' }} className="treasure">overflow +220</div></LazyLoad>
  </div>
, div);

```
在 overflow = true 的情况下，只监听了 container 的 scroll 事件。使用中应该有存在 body scroll 到特定位置应该显示 container 内元素的情况

**Comment by zemzheng** [comment]
## case
```javascript
<ul max-height="150%" style.overflow="auto"> // 一个可能高于当前 window.innerHeight 的区域
  ... forEach <LazyLoad overflow={true}><li .../></LazyLoad> // 一堆 LazyLoad 包裹的元素
</ul>
```
在 100% - 150% 部分有内容的时候，且 ul 不出滚动条的时候，这部分内容将一直 loading

### 为什么要 > 100%
A: 因为项目需要如此（组件也没有说不能这样吧）

### 为什么要 LazyLoad.oveflow = true
A: 因为 ul 区域有 max-height 限制，如果项目中内容超过就会出滚动条

**Comment by gajus** [comment]
This has been open for a while now – any plans on merging this?

**Comment by jasonslyvia** [comment]
@gajus the corresponding PR solves two issues in the same time, I should double check it to make sure everything is okay.

**Comment by asherism** [comment]
@jasonslyvia Any progress?

**Comment by jasonslyvia** [comment]
all overflow and scrollParent issue have been moved to #129 , let's discuss there
